#!/bin/sh
set -x
#
# $Id$
#
# $Log$
# Revision 2.1  1998-10-22 21:42:44+09  hayakawa
# ＲＯＭ出しバージョン(NTSC)
#
# Revision 1.1  1997-04-18 19:45:48+09  iwawaki
# Initial revision
#
#
/usr/bin/ld -r -o d_keep.o -objectlist d_keep.objs -m > d_keep.map
