#!/usr/local/bin/bash
#set -x
#
# $Id$
#

cp2() {
    if [ ! -e $1 ]; then
	echo "ファイルがありません $1"
    else
	if [ ! -e $2 -o $1 -nt $2 ]; then
	    echo    cp $1 $2
	    command cp $1 $2
	fi
    fi
}
cp() {
    SRC=$1
    DEST=$2
    SRCBASE=`basename $SRC`
    if [ -d $DEST ]; then
	cp2 $SRC $DEST/$SRCBASE
    else
	cp2 $SRC $DEST
    fi
}

#####	ＭＡＰ
     cp shape/TEXTURE/DD_MAP/dd_map_i.o .
     cp shape/TEXTURE/DD_MAP/dd_map_48x85.o .
