#!/bin/sh
set -x
#
# $Id$
#
# $Log$
# Revision 1.2  1997-04-18 21:12:37+09  iwawaki
# *** empty log message ***
#
# Revision 1.1  1997/04/18  11:52:25  iwawaki
# Initial revision
#
# Revision 1.1  1997/04/18  10:45:48  iwawaki
# Initial revision
#
# Revision 1.1  1997/04/18  10:45:48  iwawaki
# Initial revision
#
#
ld -r -o keep.o -objectlist keep.objs -m > keep.map
