#!/usr/local/bin/bash
#set -x
#
# $Id$
#

cp2() {
    if [ ! -e $1 ]; then
	echo -e "\007\033[37;41mファイルがありません $1\033[m"
    else
	if [ ! -e $2 -o $1 -nt $2 ]; then
	    echo    cp $1 $2
	    command cp $1 $2
	fi
    fi
}
cp() {
    SRC=$1
    DEST=$2
    SRCBASE=`basename $SRC`
    if [ -d $DEST ]; then
	cp2 $SRC $DEST/$SRCBASE
    else
	cp2 $SRC $DEST
    fi
}

#####	初期チェック用エラーメッセージ
     cp shape/TEXTURE/DMA_MAKE/memerrmsg/memerrmsg.o .
     cp shape/TEXTURE/DMA_MAKE/memerrmsg/locerrmsg.o .

#####	イベント制御コード
     cp /home/soejima/c/Event/change/save_list_txt.inc .
     cp /home/soejima/c/Event/tool/week_event_reg.inc .

#####	お面対応メッセージテーブル
     cp /home/soejima/c/Event/mask/vs_mask_message.inc .
     cp /home/soejima/c/Event/mask/vs_mask_label.inc .

#####	メッセージ
#if [ -r shape/MESSAGE/japan/japan.o ]; then
#     cp shape/MESSAGE/japan/table.h .
#     cp shape/MESSAGE/japan/extern.h .
#     cp shape/MESSAGE/japan/japan.o .
if [ -r shape/MESSAGE/japan2/japan2.o ]; then
     cp shape/MESSAGE/japan2/table.h .
     cp shape/MESSAGE/japan2/extern.h .
     cp shape/MESSAGE/japan2/japan2.o japan.o
else
    echo -e "\007\033[37;41m只今メッセージは更新中、または壊れています\033[m"
fi
if [ -r shape/MESSAGE/USA/USA.o ]; then
     cp shape/MESSAGE/USA/usa_table.h .
     cp shape/MESSAGE/USA/usa_extern.h .
     cp shape/MESSAGE/USA/USA.o .
else
    echo -e "\007\033[37;41m只今【ＵＳＡ版】メッセージは更新中、または壊れています\033[m"
fi


     cp shape/TEXTURE/MESSAGE/texture/texture.o .
     cp shape/TEXTURE/MESSAGE/fukidashi/fukidashi.o .
###
#2000/05/24     cp shape/TEXTURE/MESSAGE/font/font_e.o .
     cp shape/MESSAGE/font/font_e.o .
     cp shape/TEXTURE/MESSAGE/NES/nes_c.o .
#2000/03/20     cp shape/TEXTURE/MESSAGE/STAFF/staff_c.o .
     cp  shape/MESSAGE/staff/staff_c.o .
##### メッセージソースというか
     cp shape/TEXTURE/MESSAGE/NES/nes_a nes_a
     cp shape/TEXTURE/MESSAGE/NES/nes_b nes_b
#2000/03/20     cp shape/TEXTURE/MESSAGE/STAFF/staff_a staff_a
#2000/03/20     cp shape/TEXTURE/MESSAGE/STAFF/staff_b staff_b
     cp shape/MESSAGE/staff/staff_a staff_a
     cp shape/MESSAGE/staff/staff_b staff_b
