#!/usr/local/bin/bash
#set -x
#
# $Id$
#

cp2() {
    if [ ! -e $1 ]; then
	echo -e "\007\033[37;41mファイルがありません $1\033[m"
    else
	if [ ! -e $2 -o $1 -nt $2 ]; then
	    echo    cp $1 $2
	    command cp $1 $2
	fi
    fi
}
cp() {
    SRC=$1
    DEST=$2
    SRCBASE=`basename $SRC`
    if [ -d $DEST ]; then
	cp2 $SRC $DEST/$SRCBASE
    else
	cp2 $SRC $DEST
    fi
}

#####	初期チェック用エラーメッセージ
     cp shape/TEXTURE/DMA_MAKE/memerrmsg/locerrmsg.o .
     cp shape/TEXTURE/DMA_MAKE/memerrmsg/memerrmsg.o .
     cp shape/TEXTURE/DMA_MAKE/memerrmsg/memerrmsg_nes.o .
     cp shape/TEXTURE/DMA_MAKE/memerrmsg/locerrmsg_pal.o .
     cp shape/TEXTURE/DMA_MAKE/memerrmsg/memerrmsg_pal.o .

#####	イベント制御コード
     cp /home/soejima/c/Event/change/save_list_txt.inc .
     cp /home/soejima/c/Event/tool/week_event_reg.inc .

#####	お面対応メッセージテーブル
     cp /home/soejima/c/Event/mask/vs_mask_message.inc .
     cp /home/soejima/c/Event/mask/vs_mask_label.inc .

#####	メッセージ
## 日本語
#if [ -r shape/MESSAGE/japan/japan.o ]; then
#     cp shape/MESSAGE/japan/table.h .
#     cp shape/MESSAGE/japan/extern.h .
#     cp shape/MESSAGE/japan/japan.o .
if [ -r shape/MESSAGE/japan2/japan2.o ]; then
     cp shape/MESSAGE/japan2/table.h .
     cp shape/MESSAGE/japan2/extern.h .
     cp shape/MESSAGE/japan2/japan2.o japan.o
else
    echo -e "\007\033[37;41m只今メッセージは更新中、または壊れています\033[m"
fi
## 英語
if [ -r shape/MESSAGE/NES/NES.o ]; then
     cp shape/MESSAGE/NES/message_define.h .
     cp shape/MESSAGE/NES/nes_table.h .
     cp shape/MESSAGE/NES/nes_extern.h .
     cp shape/MESSAGE/NES/NES.o .
else
    echo -e "\007\033[37;41m只今【ＵＳＡ版】メッセージは更新中、または壊れています\033[m"
fi
## ＰＡＬ版：英語
if [ -r shape/MESSAGE/USA/USA.o ]; then
     cp shape/MESSAGE/USA/message_define.h .
     cp shape/MESSAGE/USA/usa_extern.h .
     cp shape/MESSAGE/USA/usa_table.o .
     cp shape/MESSAGE/USA/usa_message_data.o USA.o
else
    echo -e "\007\033[37;41m只今【ＰＡＬ版：英語】メッセージは更新中、または壊れています\033[m"
fi
## ドイツ語
if [ -r shape/MESSAGE/GER/GER.o ]; then
     cp shape/MESSAGE/GER/ger_extern.h .
     cp shape/MESSAGE/GER/ger_table.o .
     cp shape/MESSAGE/GER/ger_message_data.o GER.o
else
    echo -e "\007\033[37;41m只今【ドイツ語版】メッセージは更新中、または壊れています\033[m"
fi
## フランス語
if [ -r shape/MESSAGE/FRA/FRA.o ]; then
     cp shape/MESSAGE/FRA/fra_extern.h .
     cp shape/MESSAGE/FRA/fra_table.o .
     cp shape/MESSAGE/FRA/fra_message_data.o FRA.o
else
    echo -e "\007\033[37;41m只今【フランス語版】メッセージは更新中、または壊れています\033[m"
fi
## スペイン語
if [ -r shape/MESSAGE/SPA/SPA.o ]; then
     cp shape/MESSAGE/SPA/spa_extern.h .
     cp shape/MESSAGE/SPA/spa_table.o .
     cp shape/MESSAGE/SPA/spa_message_data.o SPA.o
else
    echo -e "\007\033[37;41m只今【スペイン語版】メッセージは更新中、または壊れています\033[m"
fi


## ＧＡＴＥＷＡＹ版
if [ -r shape/MESSAGE/NesG/NesG.o ]; then
     cp shape/MESSAGE/NesG/nesG_table.h .
     cp shape/MESSAGE/NesG/nesG_extern.h .
     cp shape/MESSAGE/NesG/NesG.o .
else
    echo -e "\007\033[37;41m只今【ＧＡＴＥＷＡＹ版】メッセージは更新中、または壊れています\033[m"
fi


     cp shape/TEXTURE/MESSAGE/texture/texture.o .
     cp shape/TEXTURE/MESSAGE/fukidashi/fukidashi.o .
###
#2000/05/24     cp shape/TEXTURE/MESSAGE/font/font_e.o .
     cp shape/MESSAGE/font/font_e.o .
     cp shape/TEXTURE/MESSAGE/NES/nes_c.o .
#2000/03/20     cp shape/TEXTURE/MESSAGE/STAFF/staff_c.o .
     cp  shape/MESSAGE/staff/staff_c.o .
##### メッセージソースというか
     cp shape/TEXTURE/MESSAGE/NES/nes_a nes_a
     cp shape/TEXTURE/MESSAGE/NES/nes_b nes_b
#
# ＳＴＡＦＦ
#2000/03/20     cp shape/TEXTURE/MESSAGE/STAFF/staff_a staff_a
#2000/03/20     cp shape/TEXTURE/MESSAGE/STAFF/staff_b staff_b
     cp shape/MESSAGE/staff/staff_a staff_a
     cp shape/MESSAGE/staff/staff_b staff_b
     cp shape/MESSAGE/staff/staff_c.o staff_c.o

     cp shape/MESSAGE/usa_staff/staff_a usa_staff_a
     cp shape/MESSAGE/usa_staff/staff_b usa_staff_b
     cp shape/MESSAGE/usa_staff/staff_c.o usa_staff_c.o

     cp shape/MESSAGE/pal_staff/staff_a pal_staff_a
     cp shape/MESSAGE/pal_staff/staff_b pal_staff_b
     cp shape/MESSAGE/pal_staff/staff_c.o pal_staff_c.o
