#!/usr/local/bin/bash
#set -x
#
# $Id$
#
# $Log$
# Revision 1.151  1998/03/23  06:04:29  takahata
# *** empty log message ***
#
# Revision 1.150  1998/03/21  06:43:33  sumiyosi
# 村人シェアード実験追加。
#
# Revision 1.149  1998/03/19  06:39:39  sakakibara
# Spot16 obj 追加
#
# Revision 1.148  1998/03/19  03:07:55  nisiwaki
# Tr.o を 追加
#
# Revision 1.147  1998/03/18  13:46:47  yoshida
# インゴー追加
#
# Revision 1.146  1998/03/17  10:40:59  takahata
# *** empty log message ***
#
# Revision 1.145  1998/03/16  05:25:59  takahata
# *** empty log message ***
#
# Revision 1.144  1998/03/16  04:58:24  komatu
# *** empty log message ***
#
# Revision 1.143  1998/03/13  10:56:27  takahata
# *** empty log message ***
#
# Revision 1.142  1998/03/13  06:32:29  takahata
# *** empty log message ***
#
# Revision 1.141  1998/03/12  12:29:10  takahata
# *** empty log message ***
#
# Revision 1.140  1998/03/11  10:04:31  takahata
# *** empty log message ***
#
# Revision 1.139  1998/03/10  12:54:28  morita
# mo
#
# Revision 1.138  1998/03/10  04:30:54  komatu
# *** empty log message ***
#
# Revision 1.137  1998/03/09  06:17:11  sakakibara
# *** empty log message ***
#
# Revision 1.136  1998/03/09  04:51:54  takahata
# *** empty log message ***
#
# Revision 1.135  1998/03/06  04:34:17  tarukado
# *** empty log message ***
#
# Revision 1.134  1998/03/04  14:00:32  yoshida
# *** empty log message ***
#
# Revision 1.133  1998/03/04  09:55:07  okajima
# *** empty log message ***
#
# Revision 1.132  1998/03/04  09:34:58  sakakibara
# *** empty log message ***
#
# Revision 1.131  1998/03/04  08:12:12  takahata
# *** empty log message ***
#
# Revision 1.130  1998/03/04  08:11:45  takahata
# *** empty log message ***
#
# Revision 1.129  1998/03/04  06:36:47  nisiwaki
# *** empty log message ***
#
# Revision 1.128  1998/03/03  14:07:27  yoshida
# *** empty log message ***
#
# Revision 1.127  1998/03/03  13:40:37  umemiya
# ブロッブ追加
#
# Revision 1.126  1998/03/03  12:45:20  umemiya
# Warningのため名前変更
#
# Revision 1.125  1998/03/03  08:38:32  nisiwaki
# *** empty log message ***
#
# Revision 1.124  1998/03/03  07:34:53  tarukado
# *** empty log message ***
#
# Revision 1.123  1998/03/02  02:09:01  umemiya
# 墓下ダンジョン・オブジェ追加
#
# Revision 1.122  1998/02/25  13:38:29  matutani
# *** empty log message ***
#
# Revision 1.121  1998/02/24  04:23:45  nisiwaki
# *** empty log message ***
#
# Revision 1.120  1998/02/21  10:41:37  tarukado
# *** empty log message ***
#
# Revision 1.119  1998/02/21  09:21:29  morita
# *** empty log message ***
#
# Revision 1.118  1998/02/20  12:40:12  umemiya
# 燭台をバンクに設定
#
# Revision 1.117  1998/02/20  07:50:43  matutani
# 魔法（炎、風、氷）
#
# Revision 1.116  1998/02/20  02:17:44  umemiya
# スポット０２オブジェクト、墓追加
#
# Revision 1.115  1998/02/19  07:32:25  nisiwaki
# ru1 を 追加
#
# Revision 1.114  1998/02/18  02:43:56  matutani
# 子馬追加
#
# Revision 1.113  1998/02/17  02:26:46  nisiwaki
# *** empty log message ***
#
# Revision 1.112  1998/02/16  09:05:52  sumiyosi
# フレイムダンサーを追加。
#
# Revision 1.111  1998/02/14  13:43:35  iwawaki
# *** empty log message ***
#
# Revision 1.110  1998/02/12  07:04:06  nisiwaki
# *** empty log message ***
#
# Revision 1.109  1998/02/12  02:43:54  morita
# fd追加
#
# Revision 1.108  1998/02/03  07:06:47  tarukado
# ガノン と ファントムガノンを分たっス！！
#
# Revision 1.107  1998/01/31  12:12:20  iwawaki
# *** empty log message ***
#
# Revision 1.106  1998/01/30  02:59:57  umemiya
# ポウ四姉妹追加
#
# Revision 1.105  1998/01/29  09:53:05  tarukado
# *** empty log message ***
#
# Revision 1.104  1998/01/29  07:58:52  tarukado
# *** empty log message ***
#
# Revision 1.103  1998/01/28  04:30:33  tarukado
# *** empty log message ***
#
# Revision 1.102  1998/01/27  07:00:42  umemiya
# 巨大魚ダンジョン・オブジェ追加
#
# Revision 1.101  1998/01/26  10:26:26  iwawaki
# 今寺町です
#
# Revision 1.100  1998/01/26  09:36:53  nisiwaki
# デモ用データ追加
#
# Revision 1.99  1998/01/22  12:02:35  umemiya
# 炎の輪追加
#
# Revision 1.98  1998/01/22  07:30:16  iwawaki
# *** empty log message ***
#
# Revision 1.97  1998/01/20  11:30:31  tarukado
# *** empty log message ***
#
# Revision 1.96  1998/01/20  10:34:14  tarukado
# *** empty log message ***
#
# Revision 1.95  1998/01/20  08:02:15  sumiyosi
# *** empty log message ***
#
# Revision 1.94  1998/01/19  12:34:08  umemiya
# オクタロックのデータを新規に変更
#
# Revision 1.93  1998/01/19  06:39:13  tarukado
# *** empty log message ***
#
# Revision 1.92  1998/01/14  05:51:46  tarukado
# *** empty log message ***
#
# Revision 1.91  1998/01/14  02:37:00  tarukado
# *** empty log message ***
#
# Revision 1.90  1998/01/13  14:11:20  iwawaki
# *** empty log message ***
#
# Revision 1.89  1998/01/12  14:08:35  iwawaki
# *** empty log message ***
#
# Revision 1.88  1998/01/08  10:46:44  umemiya
# 森の神殿、炎の神殿テクスチャ追加
#
# Revision 1.87  1998/01/07  06:09:59  sakakibara
# *** empty log message ***
#
# Revision 1.86  1998/01/05  05:09:33  iwawaki
# *** empty log message ***
#
# Revision 1.85  1997/12/24  06:34:10  sumiyosi
# 大ゼルダ追加
#
# Revision 1.84  1997/12/24  05:06:09  umemiya
# トラップ床ビュン追加
#
# Revision 1.83  1997/12/18  07:54:39  umemiya
# 時の間・オブジェ追加
#
# Revision 1.82  1997/12/18  06:07:05  umemiya
# *** empty log message ***
#
# Revision 1.81  1997/12/18  04:10:51  umemiya
# *** empty log message ***
#
# Revision 1.80  1997/12/17  07:03:14  tarukado
# *** empty log message ***
#
# Revision 1.79  1997/12/17  04:57:10  umemiya
# 森の神殿・ひねり回廊部屋追加
#
# Revision 1.78  1997/12/16  05:59:21  sumiyosi
# *** empty log message ***
#
# Revision 1.77  1997/12/16  00:54:29  matutani
# ファントムガノン馬
#
# Revision 1.76  1997/12/12  02:10:36  tarukado
# *** empty log message ***
#
# Revision 1.75  1997/12/12  01:52:00  tarukado
# *** empty log message ***
#
# Revision 1.74  1997/12/11  06:57:27  tarukado
# *** empty log message ***
#
# Revision 1.73  1997/12/04  09:42:29  umemiya
# 水の神殿・MOVEBGオブジェ追加
#
# Revision 1.72  1997/11/28  00:46:28  sumiyosi
# *** empty log message ***
#
# Revision 1.71  1997/11/26  07:33:26  umemiya
# バリ追加
#
# Revision 1.70  1997/11/18  04:46:20  sumiyosi
# *** empty log message ***
#
# Revision 1.69  1997/11/14  07:32:49  sumiyosi
# コキリ族軍団追加
#
# Revision 1.68  1997/11/12  08:21:34  umemiya
# 面クリダンジョンオブジェクト追加
#
# Revision 1.67  1997/11/12  07:03:41  sumiyosi
# *** empty log message ***
#
# Revision 1.66  1997/11/08  08:37:53  umemiya
# デクナッツ追加
#
# Revision 1.65  1997/11/07  04:05:52  iwawaki
# *** empty log message ***
#
# Revision 1.64  1997/10/25  05:44:13  iwawaki
# *** empty log message ***
#
# Revision 1.63  1997/10/21  09:14:32  matutani
# ゼルダ馬
#
# Revision 1.62  1997/10/20  10:45:48  sumiyosi
# ハイリア住民さらに追加。
#
# Revision 1.61  1997/10/19  09:03:22  iwawaki
# *** empty log message ***
#
# Revision 1.60  1997/10/17  08:26:27  sumiyosi
# ハイリアの住民追加。
#
# Revision 1.59  1997/10/16  08:44:16  sumiyosi
# En_GirlB→子ゼルダに変更。
#
# Revision 1.58  1997/10/08  14:18:04  sumiyosi
# インパ（マスク付）追加
#
# Revision 1.57  1997/10/08  02:28:05  sumiyosi
# ゴロン族追加
#
# Revision 1.56  1997/10/02  13:44:58  umemiya
# *** empty log message ***
#
# Revision 1.55  1997/10/02  12:40:30  umemiya
# デクババ追加
#
# Revision 1.54  1997/10/01  04:31:43  tarukado
# がノンドロフ ＆ アモス 追加
#
# Revision 1.53  1997/10/01  02:37:59  umemiya
# *** empty log message ***
#
# Revision 1.52  1997/10/01  02:26:14  hayakawa
# 日付比較コピー
#
# Revision 1.51  1997/09/29  11:50:51  umemiya
# 妖精ダンジョンオブジェ追加
#
# Revision 1.50  1997/09/29  10:54:54  sumiyosi
# コキリ族の女の子追加
#
# Revision 1.49  1997/09/27  02:05:28  hayakawa
# set -xをコメントアウトした
#
# Revision 1.48  1997/09/26  06:32:40  sumiyosi
# *** empty log message ***
#
# Revision 1.47  1997/09/24  07:30:46  tarukado
# *** empty log message ***
#
# Revision 1.46  1997/09/20  04:16:41  tarukado
# *** empty log message ***
#
# Revision 1.45  1997/09/19  08:57:12  tarukado
# *** empty log message ***
#
# Revision 1.44  1997/09/19  05:29:29  tarukado
# モリブリン追加
#
# Revision 1.43  1997/09/17  13:51:39  umemiya
# spot00オブジェ追加
#
# Revision 1.42  1997/09/17  07:24:54  sumiyosi
# *** empty log message ***
#
# Revision 1.41  1997/09/16  08:47:02  sumiyosi
# *** empty log message ***
#
# Revision 1.40  1997/09/12  12:29:05  matutani
# ガノン馬追加
#
# Revision 1.39  1997/09/11  06:45:09  umemiya
# 火の神殿オブジェ追加
#
# Revision 1.38  1997/09/09  11:54:28  iwawaki
# *** empty log message ***
#
# Revision 1.37  1997/09/05  06:37:10  sumiyosi
# *** empty log message ***
#
# Revision 1.36  1997/09/05  06:35:29  matutani
# *** empty log message ***
#
# Revision 1.35  1997/09/01  02:13:16  tarukado
# *** empty log message ***
#
# Revision 1.34  1997/09/01  01:03:48  tarukado
# *** empty log message ***
#
# Revision 1.33  1997/08/27  11:30:37  sumiyosi
# *** empty log message ***
#
# Revision 1.32  1997/08/27  06:05:06  sumiyosi
# *** empty log message ***
#
# Revision 1.31  1997/08/25  13:37:44  sumiyosi
# スタルチュラ追加。
#
# Revision 1.30  1997/08/25  01:51:32  sumiyosi
# *** empty log message ***
#
# Revision 1.29  1997/08/25  01:49:30  sumiyosi
# *** empty log message ***
#
# Revision 1.28  1997/08/25  01:48:38  hayakawa
# *** empty log message ***
#
# Revision 1.27  1997/08/19  09:46:25  tarukado
# *** empty log message ***
#
# Revision 1.26  1997/08/12  11:11:00  iwawaki
# *** empty log message ***
#
# Revision 1.25  1997/08/05  09:29:58  tarukado
# *** empty log message ***
#
# Revision 1.24  1997/08/04  02:38:22  iwawaki
# *** empty log message ***
#
# Revision 1.23  1997/07/30  01:25:20  tarukado
# *** empty log message ***
#
# Revision 1.22  1997/07/18  11:24:31  tarukado
# *** empty log message ***
#
# Revision 1.21  1997/07/18  01:16:01  tarukado
# *** empty log message ***
#
# Revision 1.20  1997/07/17  09:49:45  iwawaki
# *** empty log message ***
#
# Revision 1.19  1997/07/17  08:39:26  tarukado
# *** empty log message ***
#
# Revision 1.18  1997/07/17  06:25:26  tarukado
# *** empty log message ***
#
# Revision 1.17  1997/07/17  06:08:48  tarukado
# *** empty log message ***
#
# Revision 1.16  1997/07/17  02:50:13  tarukado
# *** empty log message ***
#
# Revision 1.15  1997/07/17  02:49:41  tarukado
# *** empty log message ***
#
# Revision 1.14  1997/07/17  02:35:34  tarukado
# *** empty log message ***
#
# Revision 1.13  1997/07/17  01:46:25  tarukado
# *** empty log message ***
#
# Revision 1.12  1997/07/09  08:37:57  sumiyosi
# *** empty log message ***
#
# Revision 1.11  1997/07/09  07:22:03  iwawaki
# *** empty log message ***
#
# Revision 1.10  1997/07/02  09:03:44  tarukado
# *** empty log message ***
#
# Revision 1.9  1997/07/02  08:04:50  tarukado
# *** empty log message ***
#
# Revision 1.8  1997/06/26  12:33:43  iwawaki
# *** empty log message ***
#
# Revision 1.7  1997/06/19  00:42:49  iwawaki
# *** empty log message ***
#
# Revision 1.6  1997/06/06  06:57:42  iwawaki
# *** empty log message ***
#
# Revision 1.5  1997/06/06  05:48:25  iwawaki
# *** empty log message ***
#
# Revision 1.4  1997/06/05  07:49:04  iwawaki
# *** empty log message ***
#
# Revision 1.3  1997/06/05  07:18:12  iwawaki
# *** empty log message ***
#
# Revision 1.2  1997/05/26  10:26:49  iwawaki
# *** empty log message ***
#
# Revision 1.1  1997/05/26  06:37:52  iwawaki
# Initial revision
#

cp2() {
  if [ ! -e $2 -o $1 -nt $2 ]; then
    echo    cp $1 $2
    command cp $1 $2
  fi
}
cp() {
  SRC=$1
  DEST=$2
  SRCBASE=`basename $SRC`
  if [ -d $DEST ]; then
    cp2 $SRC $DEST/$SRCBASE
  else
    cp2 $SRC $DEST
  fi
}

     cp shape/zelda_field_keep/zelda_field_keep.o Field_keep.o
     cp shape/zelda_dangeon_keep/zelda_dangeon_keep.o Dangeon_keep.o
     cp shape/zelda_link_new/Anime_Data/Anime_Data.o Link_anime_data.o

    cp shape/zelda_link_new/Skeleton/Boy/Boy.o Link_boy.o
    cp shape/zelda_link_new/Skeleton/Child/Child.o Link_child.o

#     cp /home/yoshida/gamegen/cnv/LINK/main/Boy/Boy.o Link_boy.o
#     cp /home/yoshida/gamegen/cnv/LINK/main/Child/Child.o Link_child.o

     cp shape/zelda_baby_skel/zelda_baby_skel.o Baby_skel.o 
     cp shape/zelda_box/zelda_box.o Box.o
     cp shape/zelda_dodongo/zelda_dodongo.o Dodongo.o
     cp shape/zelda_fire/zelda_fire.o Fire.o
     cp shape/zelda_human/zelda_human.o Human.o
     cp shape/zelda_ironknack/zelda_ironknack.o Ironknack.o
     cp shape/zelda_nw/zelda_nw.o Niw.o
     cp shape/zelda_rock/zelda_rock.o Rock.o
     cp shape/zelda_skelton/zelda_skelton.o Skelton.o
     cp shape/zelda_slime/zelda_slime.o Slime.o
     cp shape/zelda_soldier/zelda_soldier.o Soldier.o
     cp shape/zelda_st/zelda_st.o St.o
     cp shape/zelda_tt/zelda_tt.o Tite.o
     cp shape/zelda_rb/zelda_rb.o Reeba.o
     cp shape/zelda_ph/zelda_ph.o Peehat.o
     cp shape/zelda_horse/zelda_horse.o Horse.o
     cp shape/zelda_zf/zelda_zf.o Zf.o
     cp shape/zelda_goma/zelda_goma.o Go.o
     cp shape/zelda_kdodongo/zelda_kdodongo.o Kdodongo.o
     cp shape/zelda_zl1/zelda_zl1.o Zl1.o
     cp shape/zelda_ff/zelda_ff.o Ff.o
     cp shape/zelda_wm/zelda_wm.o Wm.o
     cp shape/zelda_po/zelda_po.o Po.o
     cp shape/zelda_oAx/zelda_oAx.o OAX.o
     cp shape/zelda_oc2/zelda_oc2.o Oc.o
     cp shape/zelda_tg2/zelda_tg2.o Tg2.o
     cp shape/zelda_kogoma/zelda_kogoma.o Gol.o
     cp shape/zelda_bubble/zelda_bubble.o Bubble.o
     cp shape/zelda_dodojr/zelda_dodojr.o Dodojr.o
     cp shape/zelda_torch2/zelda_torch2.o Torch2.o
     cp shape/zelda_bl/zelda_bl.o Bl.o
     cp shape/zelda_tp/zelda_tp.o Tp.o
     cp shape/zelda_bw/zelda_bw.o Bw.o
     cp shape/zelda_ei/zelda_ei.o Ei.o
     cp shape/zelda_horse_normal/zelda_horse_normal.o Horse_Normal.o
     cp shape/zelda_oBx/zelda_oBx.o OBX.o
     cp shape/zelda_o_anime/zelda_o_anime.o O_anime.o
     cp shape/zelda_spo04_objects/zelda_spo04_objects.o spot04_objects.o
     cp shape/zelda_ddan_objects/zelda_ddan_objects.o ddan_objects.o
     cp shape/zelda_hidan_objects/zelda_hidan_objects.o hidan_objects.o
     cp shape/zelda_horse_ganon/zelda_horse_ganon.o Horse_Ganon.o
     cp shape/zelda_oA2/zelda_oA2.o OA2.o
     cp shape/zelda_spot00_objects/zelda_spot00_objects.o spot00_objects.o
     cp shape/zelda_mb/zelda_mb.o Mb.o
     cp shape/zelda_bombf/zelda_bombf.o Bombf.o
     cp shape/zelda_sk2/zelda_sk2.o Sk2.o
     cp shape/zelda_oE1/zelda_oE1.o OE1.o
     cp shape/zelda_oE_anime/zelda_oE_anime.o OE_anime.o
     cp shape/zelda_oE2/zelda_oE2.o OE2.o
     cp shape/zelda_ydan_objects/zelda_ydan_objects.o ydan_objects.o
     cp shape/zelda_gnd/zelda_gnd.o Gnd.o
     cp shape/zelda_am/zelda_am.o Am.o
     cp shape/zelda_dekubaba/zelda_dekubaba.o Dekubaba.o
     cp shape/zelda_oF1/zelda_oF1.o OF1.o
     cp shape/zelda_oA3/zelda_oA3.o OA3.o
     cp shape/zelda_oA4/zelda_oA4.o OA4.o
     cp shape/zelda_oA5/zelda_oA5.o OA5.o
     cp shape/zelda_oA6/zelda_oA6.o OA6.o
     cp shape/zelda_oA7/zelda_oA7.o OA7.o
     cp shape/zelda_jj/zelda_jj.o Jj.o
     cp shape/zelda_oA8/zelda_oA8.o OA8.o
     cp shape/zelda_oA9/zelda_oA9.o OA9.o
     cp shape/zelda_oB2/zelda_oB2.o OB2.o
     cp shape/zelda_oB3/zelda_oB3.o OB3.o
     cp shape/zelda_oB4/zelda_oB4.o OB4.o
     cp shape/zelda_horse_zelda/zelda_horse_zelda.o Horse_Zelda.o
     cp shape/zelda_opdemo1/zelda_opdemo1.o Opening_Demo1.o
     cp shape/zelda_warp1/zelda_warp1.o Warp1.o
     cp shape/zelda_b_heart/zelda_b_heart.o B_heart.o
     cp shape/zelda_dekunuts/zelda_dekunuts.o Dekunuts.o
     cp shape/zelda_oE3/zelda_oE3.o OE3.o
     cp shape/zelda_oE4/zelda_oE4.o OE4.o
     cp shape/zelda_menkuri_objects/zelda_menkuri_objects.o menkuri_objects.o
     cp shape/zelda_oE5/zelda_oE5.o OE5.o
     cp shape/zelda_oE6/zelda_oE6.o OE6.o
     cp shape/zelda_oE7/zelda_oE7.o OE7.o
     cp shape/zelda_oE8/zelda_oE8.o OE8.o
     cp shape/zelda_oE9/zelda_oE9.o OE9.o
     cp shape/zelda_oE10/zelda_oE10.o OE10.o
     cp shape/zelda_oE11/zelda_oE11.o OE11.o
     cp shape/zelda_oE12/zelda_oE12.o OE12.o
     cp shape/zelda_vali/zelda_vali.o Vali.o
     cp shape/zelda_oA10/zelda_oA10.o OA10.o
     cp shape/zelda_oA11/zelda_oA11.o OA11.o
     cp shape/zelda_mizu_objects/zelda_mizu_objects.o mizu_objects.o
     cp shape/zelda_fantomHG/zelda_fantomHG.o FantomHG.o
#     cp shape/zelda_oB1/zelda_oB1.o OB1.o
     cp shape/zelda_sh/zelda_sh.o OB1.o
     cp shape/zelda_mori_hineri1/zelda_mori_hineri1.o mori_hineri1.o
     cp shape/zelda_bb/zelda_bb.o Bb.o
     cp shape/zelda_toki_objects/zelda_toki_objects.o toki_objects.o
     cp shape/zelda_yukabyun/zelda_yukabyun.o Yukabyun.o
     cp shape/zelda_zl2/zelda_zl2.o Zl2.o
     cp shape/zelda_mjin/zelda_mjin.o Mjin.o
     cp shape/zelda_mjin_flash/zelda_mjin_flash.o Flash_mjin.o
     cp shape/zelda_mjin_dark/zelda_mjin_dark.o Dark_mjin.o
     cp shape/zelda_mjin_flame/zelda_mjin_flame.o Flame_mjin.o
     cp shape/zelda_mjin_ice/zelda_mjin_ice.o Ice_mjin.o
     cp shape/zelda_mjin_soul/zelda_mjin_soul.o Soul_mjin.o
     cp shape/zelda_mjin_wind/zelda_mjin_wind.o Wind_mjin.o
     cp shape/zelda_mjin_oka/zelda_mjin_oka.o Oka_mjin.o
     cp shape/zelda_hidan_objects2/zelda_hidan_objects2.o hidan_objects2.o
     cp shape/zelda_hidan_objects3/zelda_hidan_objects3.o hidan_objects3.o
     cp shape/zelda_hidan_objects4/zelda_hidan_objects4.o hidan_objects4.o
     cp shape/zelda_hidan_objects5/zelda_hidan_objects5.o hidan_objects5.o
     cp shape/zelda_hidan_objects6/zelda_hidan_objects6.o hidan_objects6.o
     cp shape/zelda_mori_hineri1a/zelda_mori_hineri1a.o mori_hineri1a.o
     cp shape/zelda_mori_hineri2/zelda_mori_hineri2.o mori_hineri2.o
     cp shape/zelda_mori_hineri2a/zelda_mori_hineri2a.o mori_hineri2a.o
     cp shape/zelda_mori_objects/zelda_mori_objects.o mori_objects.o
     cp shape/zelda_mori_tex/zelda_mori_tex.o mori_tex.o
     cp shape/zelda_hidan_tex/zelda_hidan_tex.o hidan_tex.o
     cp shape/zelda_warp2/zelda_warp2.o Warp2.o
     cp shape/zelda_hata/zelda_hata.o Hata.o
     cp shape/zelda_bird/zelda_bird.o Bird.o
     cp shape/zelda_stree/zelda_stree.o Stree.o
     cp shape/zelda_kui/zelda_kui.o Kui.o
     cp shape/zelda_maruta/zelda_maruta.o Maruta.o
     cp shape/zelda_saku/zelda_saku.o Saku.o
     cp shape/zelda_wood02/zelda_wood02.o Wood02.o
     cp shape/zelda_t_wood01/zelda_t_wood01.o Twood01.o
     cp shape/zelda_kabu02/zelda_kabu02.o Kabu02.o
     cp shape/dk_board/dk_board.o Board.o
     cp shape/dk_floater/dk_floater.o Floater.o
     cp shape/dk_lightbox/dk_lightbox.o Lightbox.o
     cp shape/dk_pu_box/dk_pu_box.o Pu_box.o
     cp shape/dk_spia/dk_spia.o Spia.o
     cp shape/dk_stonebridge/dk_stonebridge.o Stonebridge.o
     cp shape/dk_trap/dk_trap.o Trap.o
     cp shape/dk_vase/dk_vase.o Vase.o
     cp shape/zelda_im/zelda_im.o Im.o
     cp shape/zelda_xc/zelda_xc.o Xc.o
     cp shape/zelda_ta/zelda_ta.o Ta.o
     cp shape/zelda_tk/zelda_tk.o Tk.o
     cp shape/zelda_vm/zelda_vm.o Vm.o
     cp shape/zelda_bv/zelda_bv.o Bv.o
     cp shape/zelda_firecircle/zelda_firecircle.o  Firecircle.o
     cp shape/zelda_efc_crystal_light/zelda_efc_crystal_light.o  efc_crystal_light.o
     cp shape/zelda_efc_fire_ball/zelda_efc_fire_ball.o  efc_fire_ball.o
     cp shape/zelda_efc_flash/zelda_efc_flash.o   efc_flash.o
     cp shape/zelda_efc_lgt_shower/zelda_efc_lgt_shower.o   efc_lgt_shower.o
     cp shape/zelda_efc_star_field/zelda_efc_star_field.o   efc_star_field.o
     cp shape/zelda_god_lgt/zelda_god_lgt.o god_lgt.o   
     cp shape/zelda_light_ring/zelda_light_ring.o light_ring.o   
     cp shape/zelda_triforce_spot/zelda_triforce_spot.o  triforce_spot.o
     cp shape/zelda_bdan_objects/zelda_bdan_objects.o bdan_objects.o
     cp shape/zelda_sd/zelda_sd.o Sd.o
     cp shape/zelda_rd/zelda_rd.o Rd.o
     cp shape/zelda_po_sisters/zelda_po_sisters.o Po_Sisters.o
     cp shape/zelda_heavy_object/zelda_heavy_object.o Heavy_object.o
     cp shape/zelda_gndd/zelda_gndd.o Gndd.o
     cp shape/zelda_fd/zelda_fd.o fd.o
     cp shape/zelda_du/zelda_du.o du.o
     cp shape/zelda_fw/zelda_fw.o fw.o
     cp shape/zelda_medal/medal.o medal.o
     cp shape/zelda_hlc/zelda_hlc.o hlc.o
     cp shape/zelda_ru1/zelda_ru1.o ru1.o
     cp shape/zelda_spot02_objects/zelda_spot02_objects.o spot02_objects.o
     cp shape/zelda_haka/zelda_haka.o Haka.o
     cp shape/zelda_magic_wind/zelda_magic_wind.o magic_wind.o
     cp shape/zelda_magic_fire/zelda_magic_fire.o magic_fire.o
     cp shape/zelda_magic_ice/zelda_magic_ice.o magic_ice.o
     cp shape/zelda_syokudai/zelda_syokudai.o syokudai.o
     cp shape/zelda_vba/zelda_vba.o fd2.o
     cp shape/zelda_dh/zelda_dh.o Dh.o
     cp shape/zelda_efc_tw/zelda_efc_tw.o efc_tw.o
     cp shape/zelda_rl/zelda_rl.o Rl.o
     cp shape/zelda_tre_lgt/zelda_tre_lgt.o demo_tre_lgt.o
     cp shape/zelda_haka_objects/zelda_haka_objects.o haka_objects.o
     cp shape/zelda_key/zelda_key.o gi_key.o
     cp shape/zelda_mir_ray/zelda_mir_ray.o mir_ray.o
     cp shape/zelda_brob/zelda_brob.o Brob.o
     cp shape/zelda_gi_jewel/zelda_gi_jewel.o gi_jewel.o
     cp shape/zelda_spot09_obj/zelda_spot09_obj.o spot09_obj.o
     cp shape/zelda_spot18_obj/zelda_spot18_obj.o spot18_obj.o
     cp shape/zelda_boss_door/zelda_boss_door.o bdoor.o
#     cp shape/zelda_va/zelda_va.o Va.o
     cp shape/zelda_dungen/zelda_dungen.o shop_dungen.o
     cp shape/zelda_spot17_obj/zelda_spot17_obj.o spot17_obj.o
     cp shape/zelda_nb/zelda_nb.o nb.o
     cp shape/zelda_mo/zelda_mo.o mo.o
     cp shape/zelda_sb/zelda_sb.o sb.o
     cp shape/zelda_gi_melody/zelda_gi_melody.o gi_melody.o
     cp shape/zelda_gi_heart/zelda_gi_heart.o gi_heart.o
     cp shape/zelda_gi_compass/zelda_gi_compass.o gi_compass.o
     cp shape/zelda_gi_bosskey/zelda_gi_bosskey.o gi_bosskey.o
     cp shape/zelda_gi_medal/zelda_gi_medal.o gi_medal.o
     cp shape/zelda_gi_nuts/zelda_gi_nuts.o gi_nuts.o
     cp shape/zelda_sa/zelda_sa.o sa.o
     cp shape/zelda_gi_hearts/zelda_gi_hearts.o gi_hearts.o
     cp shape/zelda_gi_arrowcase/zelda_gi_arrowcase.o gi_arrowcase.o
     cp shape/zelda_gi_bombpouch/zelda_gi_bombpouch.o gi_bombpouch.o
     cp shape/zelda_in/zelda_in.o In.o
     cp shape/zelda_tr/zelda_tr.o Tr.o
     cp shape/zelda_spot16_obj/zelda_spot16_obj.o spot16_obj.o
     cp shape/zelda_oE1s/zelda_oE1s.o oE1s.o
     cp shape/zelda_oE4s/zelda_oE4s.o oE4s.o
     cp shape/zelda_os_anime/zelda_os_anime.o os_anime.o
     cp shape/zelda_gi_bottle/zelda_gi_bottle.o gi_bottle.o
     cp shape/zelda_dy_obj/zelda_dy_obj.o dy_obj.o
