#!/usr/local/bin/bash
#set -x
#
# $Id$
#
# $Log$
# Revision 2.264  2000-01-13 11:18:57+09  nisiwaki
# *** empty log message ***
#
# Revision 2.263  2000-01-12 17:32:46+09  kuzuhara
# タンロンさん専用
#
# Revision 2.262  2000-01-12 14:11:09+09  iwawaki
# *** empty log message ***
#
# Revision 2.261  2000-01-11 18:05:53+09  iwawaki
# *** empty log message ***
#
# Revision 2.260  2000-01-11 14:26:44+09  nisiwaki
# *** empty log message ***
#
# Revision 2.259  2000-01-11 10:21:17+09  nisiwaki
# ゾーラドラム追加
#
# Revision 2.258  2000-01-08 15:46:38+09  iwawaki
# *** empty log message ***
#
# Revision 2.257  2000-01-08 14:24:23+09  iwawaki
# *** empty log message ***
#
# Revision 2.256  2000-01-08 13:18:47+09  sakaguti
# 思い出のペンダント
#
# Revision 2.255  2000-01-07 11:39:41+09  takesita
# リーバもともとありました。追加したのは削除。トホホ…
#
# Revision 2.254  2000-01-07 11:12:44+09  takesita
# リーバ復活！！
#
# Revision 2.253  2000-01-07 09:56:06+09  sakaguti
# 赤いクスリビン入り追加
#
# Revision 2.252  2000-01-06 20:53:46+09  iwawaki
# *** empty log message ***
#
# Revision 2.251  2000-01-06 12:29:44+09  sasaki
# デモ用持ち上げ仮面 追加
#
# Revision 2.250  2000-01-05 16:09:34+09  sasaki
# ミルクバーステージ 追加
#
# Revision 2.249  2000-01-05 15:17:59+09  nisiwaki
# ゾーラベース追加
#
# Revision 2.248  2000-01-05 14:12:49+09  sakaguti
# *** empty log message ***
#
# Revision 2.247  1999-12-28 10:54:28+09  umemiya
# 毒カエルスライム、紺碧回転部屋削除
#
# Revision 2.246  1999-12-22 17:44:16+09  iwawaki
# *** empty log message ***
#
# Revision 2.245  1999-12-22 14:24:07+09  takesita
# *** empty log message ***
#
# Revision 2.244  1999-12-22 14:22:59+09  yoshida
# *** empty log message ***
#
# Revision 2.243  1999-12-21 17:34:52+09  sakaguti
# ゲットアイテム追加
#
# Revision 2.242  1999-12-21 14:38:40+09  iwawaki
# *** empty log message ***
#
# Revision 2.241  1999-12-20 15:17:28+09  nisiwaki
# *** empty log message ***
#
# Revision 2.240  1999-12-16 18:21:19+09  sakakibara
# tokei_turret
#
# Revision 2.239  1999-12-16 14:44:27+09  umemiya
# *** empty log message ***
#
# Revision 2.238  1999-12-15 13:14:30+09  nisiwaki
# Gla 追加
#
# Revision 2.237  1999-12-15 13:04:52+09  kuzuhara
# 海賊ゲルド作成
#
# Revision 2.236  1999-12-13 20:06:53+09  sakakibara
# mbar_obj ikana_obj 追加
#
# Revision 2.235  1999-12-13 13:01:57+09  kuzuhara
# 再生リーバ作成
#
# Revision 2.234  1999-12-11 20:11:34+09  iwawaki
# *** empty log message ***
#
# Revision 2.233  1999-12-11 18:39:02+09  iwawaki
# *** empty log message ***
#
# Revision 2.232  1999-12-11 17:24:29+09  matutani
# 馬車追加
#
# Revision 2.231  1999-12-10 14:57:05+09  sakaguti
# *** empty log message ***
#
# Revision 2.230  1999-12-09 16:16:51+09  sumiyosi
# *** empty log message ***
#
# Revision 2.229  1999-12-09 15:30:05+09  sakaguti
# *** empty log message ***
#
# Revision 2.228  1999-12-09 15:02:39+09  nisiwaki
# 反射光変更
#
# Revision 2.227  1999-12-09 15:01:28+09  sumiyosi
# *** empty log message ***
#
# Revision 2.226  1999-12-08 17:28:28+09  sakakibara
# ishi, kin2_obj 追加   timeblock, fence, hampost 削除
#
# Revision 2.225  1999-12-08 10:44:41+09  kuzuhara
# 深海透明壁
#
# Revision 2.224  1999-12-07 16:09:38+09  takesita
# 張り子の牛追加
#
# Revision 2.223  1999-12-07 14:48:08+09  yoshida
# デク執事追加
#
# Revision 2.222  1999-12-07 14:29:02+09  sakaguti
# *** empty log message ***
#
# Revision 2.221  1999-12-07 11:58:41+09  umemiya
# *** empty log message ***
#
# Revision 2.220  1999-12-07 11:08:37+09  umemiya
# ビッグポウ追加
#
# Revision 2.219  1999-12-06 15:04:58+09  sakaguti
# ゲットアイテムのタツノオトシゴ、ハイラルどじょう追加。
#
# Revision 2.218  1999-12-06 11:43:53+09  takesita
# 銅鑼追加。ボワァ〜〜〜ン！！
#
# Revision 2.217  1999-12-06 10:49:54+09  kuzuhara
# うつぼ
#
# Revision 2.216  1999-12-04 16:58:08+09  yoshida
# 金のタツノオトシゴ
#
# Revision 2.215  1999-12-03 11:40:42+09  kuzuhara
# 蜂
#
# Revision 2.214  1999-12-02 14:36:39+09  sakaguti
# *** empty log message ***
#
# Revision 2.213  1999-12-02 13:29:20+09  umemiya
# 水面氷追加
#
# Revision 2.212  1999-12-02 13:28:17+09  sumiyosi
# *** empty log message ***
#
# Revision 2.211  1999-11-30 22:10:17+09  iwawaki
# *** empty log message ***
#
# Revision 2.210  1999-11-30 19:14:55+09  sasaki
# 雪山地形 追加
#
# Revision 2.209  1999-11-27 16:32:08+09  iwawaki
# *** empty log message ***
#
# Revision 2.208  1999-11-26 19:52:59+09  iwawaki
# *** empty log message ***
#
# Revision 2.207  1999-11-26 14:36:17+09  sakaguti
# *** empty log message ***
#
# Revision 2.206  1999-11-25 17:27:28+09  sakaguti
# 売りナッツ消去
#
# Revision 2.205  1999-11-25 13:30:00+09  sakaguti
# ゲットアイテムの卵、デクの盾、ゴロンの服、ゾーラの服、デクのたね、炎を削除
#
# Revision 2.204  1999-11-25 11:57:54+09  takesita
# 止め売りナッツ追加
#
# Revision 2.203  1999-11-24 21:14:26+09  sakaguti
# 売りナッツ
#
# Revision 2.202  1999-11-24 20:01:43+09  iwawaki
# *** empty log message ***
#
# Revision 2.201  1999-11-24 17:35:01+09  sakakibara
# haka_obj
#
# Revision 2.200  1999-11-24 16:26:05+09  sakaguti
# ゴロンキッド
#
# Revision 2.199  1999-11-24 16:02:47+09  nisiwaki
# zelda_mk -> zelda2_mk
#
# Revision 2.198  1999-11-24 15:39:43+09  sasaki
# サリア 大ゼルダ シーク 旧スタル バンク削除
#
# Revision 2.197  1999-11-22 10:45:48+09  nisiwaki
# 時の石碑バンク削除
#
# Revision 2.196  1999-11-20 20:03:30+09  iwawaki
# *** empty log message ***
#
# Revision 2.195  1999-11-20 13:04:31+09  sumiyosi
# *** empty log message ***
#
# Revision 2.194  1999-11-18 18:46:04+09  iwawaki
# *** empty log message ***
#
# Revision 2.193  1999-11-18 18:13:44+09  sakaguti
# *** empty log message ***
#
# Revision 2.192  1999-11-18 16:05:00+09  nisiwaki
# 鍛冶屋（ガボラ）追加
#
# Revision 2.191  1999-11-18 11:35:48+09  umemiya
# アイアンナック、デッドハンド、ドドンゴ復帰
# ビリ、バリ削除
#
# Revision 2.190  1999-11-17 14:29:57+09  yoshida
# *** empty log message ***
#
# Revision 2.189  1999-11-16 22:06:29+09  sumiyosi
# *** empty log message ***
#
# Revision 2.188  1999-11-16 14:51:39+09  sakaguti
# ゴロンの墓＆ゴロン温泉
#
# Revision 2.187  1999-11-15 19:31:01+09  takesita
# 剣道場専用丸太追加
#
# Revision 2.186  1999-11-15 16:06:47+09  takesita
# *** empty log message ***
#
# Revision 2.185  1999-11-15 14:34:55+09  sakaguti
# コロン勇者の霊
#
# Revision 2.184  1999-11-15 11:33:23+09  nisiwaki
# *** empty log message ***
#
# Revision 2.183  1999-11-15 10:38:36+09  nisiwaki
# *** empty log message ***
#
# Revision 2.182  1999-11-13 17:44:58+09  iwawaki
# *** empty log message ***
#
# Revision 2.181  1999-11-12 14:01:40+09  sakakibara
# spidertent
#
# Revision 2.180  1999-11-12 13:34:35+09  yoshida
# ポゥ音楽家追加
#
# Revision 2.179  1999-11-11 21:47:28+09  sasaki
# bsmask add
#
# Revision 2.178  1999-11-11 21:06:10+09  sumiyosi
# *** empty log message ***
#
# Revision 2.177  1999-11-11 18:00:30+09  sakaguti
# 大爆弾を追加
#
# Revision 2.176  1999-11-11 16:03:58+09  kuzuhara
# 墓地柱
#
# Revision 2.175  1999-11-11 11:50:31+09  sasaki
# delf add
#
# Revision 2.174  1999-11-09 18:58:49+09  sakaguti
# 旧ナイフを剣レベル１に変更
#
# Revision 2.173  1999-11-09 15:24:41+09  sakakibara
# goronswitch
#
# Revision 2.172  1999-11-08 13:35:33+09  kuzuhara
# ヒップループ追加
#
# Revision 2.171  1999-11-05 10:59:20+09  umemiya
# 雪魔神追加
#
# Revision 2.170  1999-11-04 20:28:25+09  sakaguti
# *** empty log message ***
#
# Revision 2.169  1999-11-02 20:12:48+09  takesita
# 墓石を追加。
#
# Revision 2.168  1999-11-01 20:01:09+09  sakakibara
# dhouse
#
# Revision 2.167  1999-11-01 16:34:26+09  yoshida
# ダンペイイベント用オブジェクト追加
#
# Revision 2.166  1999-11-01 13:01:05+09  sumiyosi
# *** empty log message ***
#
# Revision 2.165  1999-10-29 18:36:36+09  umemiya
# *** empty log message ***
#
# Revision 2.164  1999-10-28 17:31:24+09  sasaki
# スタル アニメ分割
#
# Revision 2.163  1999-10-28 14:42:41+09  sakaguti
# *** empty log message ***
#
# Revision 2.162  1999-10-28 09:45:06+09  iwawaki
# *** empty log message ***
#
# Revision 2.161  1999-10-25 16:55:42+09  yoshida
# *** empty log message ***
#
# Revision 2.160  1999-10-25 11:49:32+09  umemiya
# 白銀の砦・ボス追加
#
# Revision 2.159  1999-10-25 10:13:40+09  nisiwaki
# *** empty log message ***
#
# Revision 2.158  1999-10-22 16:04:12+09  sakakibara
# comb hana
#
# Revision 2.157  1999-10-22 15:15:58+09  nisiwaki
# *** empty log message ***
#
# Revision 2.156  1999-10-22 14:52:35+09  nisiwaki
# *** empty log message ***
#
# Revision 2.155  1999-10-22 14:07:18+09  nisiwaki
# 巨人追加
#
# Revision 2.154  1999-10-21 22:06:29+09  yoshida
# *** empty log message ***
#
# Revision 2.153  1999-10-21 21:43:11+09  yoshida
# じいちゃんディレクトリー変更
#
# Revision 2.152  1999-10-20 09:41:09+09  nisiwaki
# 雪山の木追加
#
# Revision 2.151  1999-10-19 11:33:07+09  kuzuhara
# 町内止め兵士できたー
#
# Revision 2.150  1999-10-15 11:49:38+09  umemiya
# 宝箱屋・オブジェ、水中デドハンド追加
#
# Revision 2.149  1999-10-14 18:15:52+09  sakakibara
# lightblock
#
# Revision 2.148  1999-10-14 17:14:50+09  sakaguti
# 月の石、土地の権利書を追加。
#
# Revision 2.147  1999-10-14 15:07:29+09  sumiyosi
# *** empty log message ***
#
# Revision 2.146  1999-10-08 15:40:59+09  nisiwaki
# *** empty log message ***
#
# Revision 2.145  1999-10-08 15:40:19+09  nisiwaki
# *** empty log message ***
#
# Revision 2.144  1999-10-08 13:00:55+09  sakakibara
# market_obj
#
# Revision 2.143  1999-10-07 21:38:10+09  yoshida
# *** empty log message ***
#
# Revision 2.142  1999-10-07 19:25:24+09  sakaguti
# *** empty log message ***
#
# Revision 2.141  1999-10-05 10:54:08+09  umemiya
# 大ツララ追加
#
# Revision 2.140  1999-10-05 10:32:24+09  kuzuhara
# 外伝用兵士バンク作ったナリ
#
# Revision 2.139  1999-10-04 20:59:26+09  sakaguti
# （元）宝屋店員、長髪の店員、（元）釣堀屋店員、（元）店員
# 追加
#
# Revision 2.138  1999-10-01 15:44:40+09  sakakibara
# visiblock
#
# Revision 2.137  1999-09-30 13:49:01+09  sakakibara
# dkjail_obj
#
# Revision 2.136  1999-09-27 19:34:33+09  kuzuhara
# パメット作成
#
# Revision 2.135  1999-09-27 10:46:27+09  umemiya
# 蓮追加
#
# Revision 2.134  1999-09-24 17:30:28+09  kuzuhara
# cp shape/zelda2_cs/zelda2_cs.o cs.o てな、カンジに変更
#
# Revision 2.133  1999-09-24 16:15:42+09  sakaguti
# zelda_rs/zelda_rs.o → zelda2_rsn/zelda2_rsn.o に変えた。
#
# Revision 2.132  1999-09-24 15:13:11+09  sakakibara
# tokei_step
#
# Revision 2.131  1999-09-22 20:58:00+09  umemiya
# オコリナッツのシェイプ変更
#
# Revision 2.130  1999-09-22 20:31:05+09  sumiyosi
# *** empty log message ***
#
# Revision 2.129  1999-09-22 16:44:05+09  umemiya
# 白銀眼鏡壁を削除
#
# Revision 2.128  1999-09-21 19:45:00+09  sakaguti
# お面屋、新規登録
#
# Revision 2.127  1999-09-21 19:41:10+09  sasaki
# *** empty log message ***
#
# Revision 2.126  1999-09-21 12:11:05+09  takesita
# 風車小屋おじさんミニゲーム的追加。
#
# Revision 2.125  1999-09-14 15:02:57+09  takesita
# Fu_Kaiten.o追加
#
# Revision 2.124  1999-09-13 14:49:50+09  sakaguti
# 弓矢変更。zelda_gi_bow→zelda2_gi_bow
#
# Revision 2.123  1999-09-10 15:12:35+09  sakakibara
# オープニングダンジョン・オブジェクト
#
# Revision 2.122  1999-09-08 11:05:10+09  iwawaki
# *** empty log message ***
#
# Revision 2.121  1999-09-01 20:18:32+09  iwawaki
# *** empty log message ***
#
# Revision 2.120  1999-09-01 18:42:47+09  iwawaki
# *** empty log message ***
#
# Revision 2.119  1999-09-01 18:40:34+09  iwawaki
# *** empty log message ***
#
# Revision 2.118  1999-09-01 15:04:30+09  iwawaki
# *** empty log message ***
#
# Revision 2.117  1999-08-30 14:43:22+09  umemiya
# 止めダイオクタ追加
#
# Revision 2.116  1999-08-19 21:43:01+09  matutani
# *** empty log message ***
#
# Revision 2.115  1999-08-09 20:40:04+09  matutani
# zelda_in.oをzelda2_in.oにした。
#
# Revision 2.114  1999-08-09 17:05:08+09  sakaguti
# 犬変えた。
#
# Revision 2.113  1999-08-09 15:41:10+09  takesita
# Ma1.oのコピーもとをかえました。
#
# Revision 2.112  1999-08-06 18:02:50+09  sakakibara
# レース壷
#
# Revision 2.111  1999-08-06 09:11:46+09  sakaguti
# *** empty log message ***
#
# Revision 2.110  1999-08-05 16:51:43+09  takesita
# フーセンポー追加。
#
# Revision 2.109  1999-08-04 14:04:25+09  sakakibara
# デクナッツシティ・オブジェクト
#
# Revision 2.108  1999-07-29 17:21:07+09  sasaki
# *** empty log message ***
#
# Revision 2.107  1999-07-28 21:52:06+09  yoshida
# ビーバー＆小枝 追加
#
# Revision 2.106  1999-07-28 21:17:51+09  yoshida
# *** empty log message ***
#
# Revision 2.105  1999-07-28 14:51:27+09  umemiya
# デクナッツのディレクトリ変更
#
# Revision 2.104  1999-07-28 09:52:21+09  takesita
# リ─デッドのシェープうつしました。
#
# Revision 2.103  1999-07-27 15:31:38+09  iwawaki
# *** empty log message ***
#
# Revision 2.102  1999-07-26 15:52:31+09  nisiwaki
# ゲルドＢの場所変更
#
# Revision 2.101  1999-07-26 15:40:36+09  sakaguti
# *** empty log message ***
#
# Revision 2.100  1999-07-23 17:22:05+09  sakakibara
# 時計塔の扉
#
# Revision 2.99  1999-07-23 10:53:32+09  soejima
# zelda_mag → ZELDA_MAG2 に変更
#
# Revision 2.98  1999-07-22 16:15:19+09  sakaguti
# 赤いくすり入りビン追加
#
# Revision 2.97  1999-07-21 11:12:27+09  nisiwaki
# Obj_Moguri.o の 内容変更
#
# Revision 2.96  1999-07-21 10:06:12+09  nisiwaki
# 猿追加
#
# Revision 2.95  1999-07-20 10:59:14+09  iwawaki
# *** empty log message ***
#
# Revision 2.94  1999-07-16 17:07:41+09  takesita
# スタルキッドのシェープをzelda_skbをzelda2_skbにしました。
#
# Revision 2.93  1999-07-15 11:39:50+09  sasaki
# スタルキッド（改） 追加
#
# Revision 2.92  1999-07-14 14:25:32+09  matutani
# 馬レースチェックバンク追加
#
# Revision 2.91  1999-07-09 15:10:09+09  umemiya
# ポウ削除、毒カエルスライム追加
#
# Revision 2.90  1999-07-08 17:37:22+09  sakakibara
# 白銀の砦
#
# Revision 2.89  1999-07-06 16:42:49+09  nisiwaki
# zelda_aniを zelda2_aniに変更
#
# Revision 2.88  1999-07-05 15:57:20+09  sumiyosi
# *** empty log message ***
#
# Revision 2.87  1999-07-02 14:39:17+09  matutani
# zelda_hlcをzelda2_hlcにした。
#
# Revision 2.86  1999-06-30 15:16:04+09  kuzuhara
# アイゴール作成
#
# Revision 2.85  1999-06-30 11:43:47+09  nisiwaki
# MOGURI 追加
#
# Revision 2.84  1999-06-25 11:15:51+09  umemiya
# ブロッブ削除して、時計塔内・回転廊下追加
#
# Revision 2.83  1999-06-16 15:27:26+09  nisiwaki
# Ta.o を 変更
#
# Revision 2.82  1999-06-09 14:08:08+09  yoshida
# デクナッツ執事追加
#
# Revision 2.81  1999-06-08 15:40:20+09  umemiya
# ダイオクタ削除し、ビッグスライム追加
#
# Revision 2.80  1999-06-04 14:32:16+09  yoshida
# *** empty log message ***
#
# Revision 2.79  1999-06-04 10:11:10+09  sumiyosi
# *** empty log message ***
#
# Revision 2.78  1999-06-01 13:11:31+09  umemiya
# *** empty log message ***
#
# Revision 2.77  1999-06-01 11:59:21+09  umemiya
# field40オブジェ追加
#
# Revision 2.76  1999-05-27 14:57:33+09  nisiwaki
# EN_FALL 追加
#
# Revision 2.75  1999-05-26 17:12:59+09  sakakibara
# *** empty log message ***
#
# Revision 2.74  1999-05-24 11:15:14+09  sumiyosi
# *** empty log message ***
#
# Revision 2.73  1999-05-19 15:16:56+09  sakakibara
# 流氷追加
#
# Revision 2.72  1999-05-19 11:21:23+09  yoshida
# ワープ渦追加
#
# Revision 2.71  1999-05-17 16:33:04+09  takesita
# フーセンマン（Bal.o）追加
#
# Revision 2.70  1999-05-11 14:59:28+09  yoshida
# 紺碧オブジェクト追加
#
# Revision 2.69  1999-05-07 10:21:54+09  kuzuhara
# 水効果？作成
#
# Revision 2.68  1999-05-06 17:26:39+09  sakakibara
# 時のブロック移動
#
# Revision 2.67  1999-04-28 18:22:18+09  umemiya
# ボムチュウリアル追加
#
# Revision 2.66  1999-04-27 21:47:17+09  iwawaki
# *** empty log message ***
#
# Revision 2.65  1999-04-27 17:13:19+09  kuzuhara
# 渓谷柵作成
#
# Revision 2.64  1999-04-26 14:33:01+09  nisiwaki
# 時の石碑追加
#
# Revision 2.63  1999-04-22 21:56:16+09  sumiyosi
# *** empty log message ***
#
# Revision 2.62  1999-04-22 11:55:57+09  nisiwaki
# ステンドグラス
#
# Revision 2.61  1999-04-22 11:00:16+09  nisiwaki
# スタルキッドの絵追加
#
# Revision 2.60  1999-04-21 13:43:49+09  umemiya
# はしご、クロスケ追加
#
# Revision 2.59  1999-04-16 11:35:23+09  kuzuhara
# ウィズローブとブロック作成
#
# Revision 2.58  1999-04-15 21:04:42+09  sumiyosi
# 子供ナッツ追加。
#
# Revision 2.57  1999-04-15 18:19:48+09  sumiyosi
# *** empty log message ***
#
# Revision 2.56  1999-04-15 11:40:21+09  nisiwaki
# 石碑関係のオブジェ
#
# Revision 2.55  1999-04-14 17:24:32+09  umemiya
# コウモリ追加
#
# Revision 2.54  1999-04-14 17:04:42+09  matutani
# 宝箱シェイプ新版へ
#
# Revision 2.53  1999-04-14 13:42:16+09  iwawaki
# *** empty log message ***
#
# Revision 2.52  1999-04-13 19:06:39+09  sasaki
# *** empty log message ***
#
# Revision 2.51  1999-04-12 11:10:21+09  kuzuhara
# 爆夫作成
#
# Revision 2.50  1999-04-09 17:21:12+09  sasaki
# *** empty log message ***
#
# Revision 2.49  1999-04-08 11:09:44+09  sasaki
# *** empty log message ***
#
# Revision 2.48  1999-04-08 10:43:45+09  sasaki
# *** empty log message ***
#
# Revision 2.47  1999-04-08 10:42:09+09  sasaki
# *** empty log message ***
#
# Revision 2.46  1999-04-08 10:41:09+09  sasaki
# *** empty log message ***
#
# Revision 2.45  1999-04-07 17:48:41+09  sakakibara
# フィールド木箱 追加
#
# Revision 2.44  1999-04-05 13:14:26+09  iwawaki
# *** empty log message ***
#
# Revision 2.43  1999-03-31 21:14:04+09  sumiyosi
# *** empty log message ***
#
# Revision 2.42  1999-03-31 14:15:18+09  kuzuhara
# ピラニア作成
#
# Revision 2.41  1999-03-31 10:23:57+09  sumiyosi
# *** empty log message ***
#
# Revision 2.40  1999-03-29 13:18:37+09  umemiya
# スライム追加
#
# Revision 2.39  1999-03-25 20:30:36+09  iwawaki
# *** empty log message ***
#
# Revision 2.38  1999-03-25 13:33:26+09  umemiya
# 紺碧の砦・回転部屋追加
#
# Revision 2.37  1999-03-24 21:42:22+09  sumiyosi
# *** empty log message ***
#
# Revision 2.36  1999-03-23 15:54:26+09  umemiya
# 氷ブロック追加
#
# Revision 2.35  1999-03-18 15:17:28+09  umemiya
# オクタロックzelda_oc2をzelda2_ocへ
#
# Revision 2.34  1999-03-16 22:13:59+09  sumiyosi
# *** empty log message ***
#
# Revision 2.33  1999-03-15 16:55:37+09  yoshida
# ひよこちゃんzelda_nwcをzelda2_nwcへ
#
# Revision 2.32  1999-03-15 16:30:32+09  sakakibara
# *** empty log message ***
#
# Revision 2.31  1999-03-11 16:06:36+09  sakakibara
# *** empty log message ***
#
# Revision 2.30  1999-03-10 16:11:23+09  kuzuhara
# 人食い水仙作成
#
# Revision 2.29  1999-03-08 21:51:21+09  sumiyosi
# *** empty log message ***
#
# Revision 2.28  1999-03-05 16:33:25+09  kuzuhara
# ボス領域確保
#
# Revision 2.27  1999-03-04 20:13:19+09  sumiyosi
# *** empty log message ***
#
# Revision 2.26  1999-03-04 11:39:34+09  umemiya
# クモの巣追加
#
# Revision 2.25  1999-03-03 15:03:17+09  umemiya
# つらら復帰
#
# Revision 2.24  1999-03-02 17:51:15+09  sakakibara
# *** empty log message ***
#
# Revision 2.23  1999-03-02 15:57:27+09  yoshida
# 間違いを修正
#
# Revision 2.22  1999-03-02 14:07:19+09  yoshida
# zelda_mmをzelda2_mmに変更。
#
# Revision 2.21  1999-03-02 14:05:41+09  yoshida
# *** empty log message ***
#
# Revision 2.20  1999-03-01 17:08:26+09  sakakibara
# *** empty log message ***
#
# Revision 2.19  1999-03-01 13:06:57+09  kuzuhara
# 騎士＆ワープタグ
#
# Revision 2.18  1999-02-25 09:59:58+09  kuzuhara
# 暗殺者作成
#
# Revision 2.17  1999-02-22 17:25:21+09  iwawaki
# *** empty log message ***
#
# Revision 2.16  1999-02-22 17:24:38+09  iwawaki
# *** empty log message ***
#
# Revision 2.15  1999-02-19 16:05:50+09  kuzuhara
# 炎の壁
#
# Revision 2.14  1999-02-15 17:20:13+09  iwawaki
# *** empty log message ***
#
# Revision 2.13  1999-02-15 17:01:49+09  sakakibara
# *** empty log message ***
#
# Revision 2.12  1999-02-15 15:01:57+09  sakakibara
# *** empty log message ***
#
# Revision 2.11  1999-02-15 09:59:21+09  sakakibara
# *** empty log message ***
#
# Revision 2.10  1999-02-15 09:35:11+09  iwawaki
# *** empty log message ***
#
# Revision 2.9  1999-02-08 11:44:01+09  sakakibara
# ダンジョンユニットＯＢＪ追加
#
# Revision 2.8  1999-02-03 17:13:05+09  kuzuhara
# 切り裂きバッタ作成
#
# Revision 2.7  1999-02-02 15:41:59+09  iwawaki
# *** empty log message ***
#
# Revision 2.6  1999-01-27 10:32:32+09  iwawaki
# *** empty log message ***
#
# Revision 2.5  1998-10-28 18:33:51+09  komatu
# du_PAL.oの追加
#
# Revision 2.4  1998-10-28 13:30:23+09  okajima
# *** empty log message ***
#
# Revision 2.3  1998/10/28 03:46:57  komatu
# PAL用シェイプデータXc_pal.oの追加の間違いを修正
#
# Revision 2.2  1998-10-27 14:20:50+09  komatu
# PAL用シェイプデータXc_pal.oの追加
#
# Revision 2.1  1998-10-22 21:42:44+09  hayakawa
# ＲＯＭ出しバージョン(NTSC)
#
# Revision 1.319  1998-10-14 14:20:07+09  matutani
# Skelton.o削除
#
# Revision 1.318  1998-10-09 16:51:50+09  komatu
# gjyo_objects.o を Gjyo_objects.oに
# 改名した。
#
# Revision 1.317  1998-09-23 00:47:28+09  sumiyosi
# *** empty log message ***
#
# Revision 1.316  1998-09-18 21:44:26+09  sakakibara
# 時の歌ブロック
#
# Revision 1.315  1998-09-15 17:08:10+09  nisiwaki
# *** empty log message ***
#
# Revision 1.314  1998-09-14 15:13:35+09  takahata
# *** empty log message ***
#
# Revision 1.313  1998-09-07 11:30:40+09  sumiyosi
# *** empty log message ***
#
# Revision 1.312  1998-09-05 14:34:00+09  nisiwaki
# *** empty log message ***
#
# Revision 1.311  1998-09-03 20:16:29+09  umemiya
# 怪鳥グエー追加
#
# Revision 1.310  1998-09-02 21:47:45+09  tarukado
# *** empty log message ***
#
# Revision 1.309  1998-09-02 12:00:13+09  umemiya
# *** empty log message ***
#
# Revision 1.308  1998-09-01 17:58:15+09  takahata
# *** empty log message ***
#
# Revision 1.307  1998-09-01 09:48:11+09  yoshida
# ゴシップストーン追加
#
# Revision 1.306  1998-08-26 21:42:33+09  umemiya
# 墓下ダンジョンドア追加
#
# Revision 1.305  1998-08-26 11:15:38+09  komatu
# *** empty log message ***
#
# Revision 1.304  1998-08-26 11:05:25+09  komatu
# *** empty log message ***
#
# Revision 1.303  1998-08-26 00:34:00+09  sumiyosi
# 敵(群れ、カップル、ベビースタル、ワーウルフ)追加。
#
# Revision 1.302  1998-08-24 16:58:20+09  umemiya
# 作曲家ポウ追加
#
# Revision 1.301  1998-08-22 17:30:07+09  yoshida
# *** empty log message ***
#
# Revision 1.300  1998-08-22 17:04:24+09  okajima
# *** empty log message ***
#
# Revision 1.299  1998-08-22 15:45:36+09  takahata
# *** empty log message ***
#
# Revision 1.298  1998-08-21 21:51:07+09  komatu
# *** empty log message ***
#
# Revision 1.297  1998-08-21 15:28:02+09  takahata
# *** empty log message ***
#
# Revision 1.296  1998-08-21 14:34:59+09  okajima
# *** empty log message ***
#
# Revision 1.295  1998-08-20 15:44:28+09  nisiwaki
# Efc_Doughnut.o 追加
#
# Revision 1.294  1998-08-20 14:58:06+09  nisiwaki
# Demo_Kekkai.o 追加
#
# Revision 1.293  1998-08-20 13:56:54+09  umemiya
# フィールドポウ追加
#
# Revision 1.292  1998-08-20 11:41:00+09  kuzuhara
# ボムチュウ屋見えない壁
#
# Revision 1.291  1998-08-19 18:51:25+09  takahata
# *** empty log message ***
#
# Revision 1.290  1998-08-18 16:05:25+09  takahata
# *** empty log message ***
#
# Revision 1.289  1998-08-18 11:38:36+09  kuzuhara
# デグナッツのお面品評会
#
# Revision 1.288  1998-08-17 21:07:05+09  sakakibara
# ｓｐｏｔ１１ オブジェクト と据置の木箱追加
#
# Revision 1.287  1998-08-17 16:49:01+09  yoshida
# *** empty log message ***
#
# Revision 1.286  1998-08-17 16:46:53+09  yoshida
# *** empty log message ***
#
# Revision 1.285  1998-08-17 16:44:51+09  yoshida
# SPOT01オブジェクトその２追加
#
# Revision 1.284  1998-08-12 14:44:01+09  sakakibara
# 邪神像ダンジョン 鉄柱と鉄椅子 & ドア
#
# Revision 1.283  1998-08-11 12:54:11+09  kuzuhara
# 犬やら鶏小娘やら
#
# Revision 1.282  1998-08-10 13:46:26+09  tarukado
# *** empty log message ***
#
# Revision 1.281  1998-08-08 16:05:20+09  umemiya
# 売りナッツ追加
#
# Revision 1.280  1998-08-07 19:35:40+09  nisiwaki
# Gla 追加
#
# Revision 1.279  1998-08-07 14:33:12+09  umemiya
# SPOT00・こわれた橋追加
#
# Revision 1.278  1998-08-06 20:07:33+09  takahata
# *** empty log message ***
#
# Revision 1.277  1998-08-06 17:58:48+09  umemiya
# ヒントナッツ追加
#
# Revision 1.276  1998-08-06 17:27:19+09  sakakibara
# ｓｐｏｔ１２ オブジェクト & 汎用爆弾岩追加
#
# Revision 1.275  1998-08-06 11:40:47+09  umemiya
# SPOT05オブジェクト追加
#
# Revision 1.274  1998-08-05 18:14:16+09  kuzuhara
# ボムチュウアルバイトねーちゃん作成
#
# Revision 1.273  1998-08-04 13:12:26+09  umemiya
# ダイオクタ追加
#
# Revision 1.272  1998-08-03 17:54:46+09  nisiwaki
# SSH 追加
#
# Revision 1.271  1998-08-03 11:50:10+09  okajima
# *** empty log message ***
#
# Revision 1.270  1998-07-31 20:52:57+09  takahata
# *** empty log message ***
#
# Revision 1.269  1998-07-31 11:19:39+09  kuzuhara
# 魚追加
#
# Revision 1.268  1998-07-30 11:51:55+09  komatu
# Ecの追加
#
# Revision 1.267  1998-07-30 11:32:27+09  takahata
# *** empty log message ***
#
# Revision 1.266  1998-07-29 13:30:13+09  komatu
# Zgの追加
#
# Revision 1.265  1998-07-23 17:21:56+09  kuzuhara
# 宝箱屋作成
#
# Revision 1.264  1998-07-23 13:03:46+09  kuzuhara
# 案山子
#
# Revision 1.263  1998-07-21 16:14:43+09  kuzuhara
# ガノン２作成
#
# Revision 1.262  1998-07-21 11:27:25+09  takahata
# *** empty log message ***
#
# Revision 1.261  1998-07-20 15:57:05+09  takahata
# *** empty log message ***
#
# Revision 1.260  1998-07-20 15:12:33+09  okajima
# *** empty log message ***
#
# Revision 1.259  1998-07-20 15:00:12+09  komatu
# 大ゼルダのアニメバンクを別にした
#
# Revision 1.258  1998-07-18 15:32:37+09  nisiwaki
# *** empty log message ***
#
# Revision 1.257  1998-07-17 11:23:56+09  komatu
# *** empty log message ***
#
# Revision 1.256  1998-07-16 21:28:21+09  soejima
# *** empty log message ***
#
# Revision 1.255  1998-07-15 15:09:51+09  takahata
# *** empty log message ***
#
# Revision 1.254  1998-07-15 13:54:45+09  yoshida
# *** empty log message ***
#
# Revision 1.253  1998-07-14 19:58:36+09  nisiwaki
# js 追加
#
# Revision 1.252  1998-07-14 11:58:10+09  takahata
# *** empty log message ***
#
# Revision 1.251  1998-07-13 14:28:19+09  takahata
# *** empty log message ***
#
# Revision 1.250  1998-07-09 14:52:20+09  takahata
# *** empty log message ***
#
# Revision 1.249  1998-07-09 14:26:28+09  sumiyosi
# *** empty log message ***
#
# Revision 1.248  1998-07-08 17:03:08+09  yoshida
# 吸い込み渦 潮吹 追加
#
# Revision 1.247  1998-07-07 21:52:31+09  umemiya
# ガノン内部・オブジェ追加
#
# Revision 1.246  1998-07-03 17:16:38+09  takahata
# *** empty log message ***
#
# Revision 1.245  1998-07-02 15:53:39+09  takahata
# *** empty log message ***
#
# Revision 1.244  1998-07-02 15:47:51+09  nisiwaki
# Fu 風車小屋の男
#
# Revision 1.243  1998-06-30 17:56:20+09  nisiwaki
# *** empty log message ***
#
# Revision 1.242  1998-06-29 20:38:19+09  umemiya
# ガノン城・オブジェ追加
#
# Revision 1.241  1998-06-26 15:29:24+09  takahata
# *** empty log message ***
#
# Revision 1.240  1998-06-25 19:18:07+09  kuzuhara
# 爆破看板作成
#
# Revision 1.239  1998-06-24 20:32:24+09  okajima
# 地名テロップのテクスチャを変えた（日本語、英語混在）
#
# Revision 1.238  1998-06-24 11:46:07+09  takahata
# *** empty log message ***
#
# Revision 1.237  1998-06-23 21:56:45+09  sakakibara
# *** empty log message ***
#
# Revision 1.236  1998-06-22 16:25:36+09  sumiyosi
# インゴーとめ柵追加。
#
# Revision 1.235  1998-06-20 16:39:00+10  takahata
# *** empty log message ***
#
# Revision 1.234  1998-06-18 22:17:11+09  umemiya
# フォールマスターを新シェイプに変更
#
# Revision 1.233  1998-06-18 13:07:32+09  komatu
# OF1をけした
#
# Revision 1.232  1998-06-16 18:36:07+09  umemiya
# 墓下子供ダンジョンオブジェ追加
#
# Revision 1.231  1998-06-16 12:05:59+09  nisiwaki
# たくさん増やした
#
# Revision 1.230  1998-06-15 17:32:51+09  nisiwaki
# *** empty log message ***
#
# Revision 1.229  1998-06-15 13:27:03+09  takahata
# *** empty log message ***
#
# Revision 1.228  1998-06-15 11:44:43+09  sakakibara
# *** empty log message ***
#
# Revision 1.227  1998-06-11 09:50:02+09  nisiwaki
# すいません
#
# Revision 1.226  1998-06-10 16:26:10+09  nisiwaki
# *** empty log message ***
#
# Revision 1.225  1998-06-10 10:54:07+09  takahata
# *** empty log message ***
#
# Revision 1.224  1998-06-09 20:51:53+09  kuzuhara
# ヤブサメスコア登録
#
# Revision 1.223  1998-06-09 14:57:59+09  nisiwaki
# *** empty log message ***
#
# Revision 1.222  1998-06-08 10:44:23+09  sumiyosi
# *** empty log message ***
#
# Revision 1.221  1998-06-05 23:20:23+10  sumiyosi
# *** empty log message ***
#
# Revision 1.220  1998-06-04 16:17:06+10  yoshida
# *** empty log message ***
#
# Revision 1.219  1998-06-04 14:19:16+09  umemiya
# 墓下リレーオブジェ追加
#
# Revision 1.218  1998-06-04 13:54:41+09  takahata
# *** empty log message ***
#
# Revision 1.217  1998-06-03 23:08:45+09  yoshida
# *** empty log message ***
#
# Revision 1.216  1998-06-03 11:20:12+09  nisiwaki
# *** empty log message ***
#
# Revision 1.215  1998-06-02 09:12:38+09  sumiyosi
# 修正。
#
# Revision 1.214  1998-06-01 23:47:04+10  sumiyosi
# ねえちゃん、おじさん追加。
#
# Revision 1.213  1998-06-01 20:11:45+10  hayakawa
# object_hidan_objects[456]消した
#
# Revision 1.212  1998-06-01 16:41:50+09  sakakibara
# Ｓｐｏｔ０８ オブジェクト追加
#
# Revision 1.211  1998-05-29 13:55:38+09  takahata
# *** empty log message ***
#
# Revision 1.210  1998-05-28 13:53:29+09  takahata
# *** empty log message ***
#
# Revision 1.209  1998-05-16 11:22:16+09  iwawaki
# *** empty log message ***
#
# Revision 1.208  1998/05/13 10:28:32  takahata
# *** empty log message ***
#
# Revision 1.207  1998-05-13 15:38:56+09  takahata
# *** empty log message ***
#
# Revision 1.206  1998-05-13 10:23:43+09  nisiwaki
# *** empty log message ***
#
# Revision 1.205  1998/05/12 14:19:03  sumiyosi
# *** empty log message ***
#
# Revision 1.204  1998/05/12 10:01:48  komatu
# *** empty log message ***
#
# Revision 1.203  1998-05-12 15:25:20+09  komatu
# *** empty log message ***
#
# Revision 1.202  1998-05-11 22:42:10+09  sumiyosi
# *** empty log message ***
#
# Revision 1.201  1998/05/08 05:01:34  takahata
# *** empty log message ***
#
# Revision 1.200  1998-05-07 15:06:54+09  takahata
# *** empty log message ***
#
# Revision 1.199  1998-05-06 17:39:14+09  umemiya
# 馬ジャンプ柵追加
#
# Revision 1.198  1998-05-06 15:24:14+09  sumiyosi
# キングゾーラ追加
#
# Revision 1.197  1998/04/30 00:17:16  sumiyosi
# *** empty log message ***
#
# Revision 1.196  1998/04/28 02:25:38  kuzuhara
# カカリコ、ゾーラゲート作成
#
# Revision 1.195  1998-04-24 14:15:10+09  iwawaki
# *** empty log message ***
#
# Revision 1.194  1998/04/23 09:48:50  kuzuhara
# ごめん
#
# Revision 1.193  1998-04-23 18:47:10+09  kuzuhara
# すみません
#
# Revision 1.192  1998-04-23 18:46:04+09  kuzuhara
# spot01追加
#
# Revision 1.191  1998-04-22 18:37:33+09  takahata
# *** empty log message ***
#
# Revision 1.190  1998-04-21 11:57:03+09  takahata
# *** empty log message ***
#
# Revision 1.189  1998-04-20 16:56:18+09  takahata
# *** empty log message ***
#
# Revision 1.188  1998-04-17 19:12:50+09  sakakibara
# *** empty log message ***
#
# Revision 1.187  1998/04/17 08:04:17  takahata
# *** empty log message ***
#
# Revision 1.186  1998-04-17 11:28:10+09  takahata
# *** empty log message ***
#
# Revision 1.185  1998-04-17 10:54:19+09  nisiwaki
# Demo_6K, object_demo_6k 追加
#
# Revision 1.184  1998/04/15 09:54:05  okajima
# *** empty log message ***
#
# Revision 1.183  1998/04/15 09:00:53  sumiyosi
# *** empty log message ***
#
# Revision 1.182  1998/04/15 03:07:41  nisiwaki
# 魔法関係 削除
#
# Revision 1.181  1998/04/14 09:22:47  takahata
# *** empty log message ***
#
# Revision 1.180  1998/04/14 08:48:15  okajima
# *** empty log message ***
#
# Revision 1.179  1998/04/14 08:29:44  okajima
# *** empty log message ***
#
# Revision 1.178  1998/04/13 02:33:15  takahata
# *** empty log message ***
#
# Revision 1.177  1998/04/10 05:21:18  nisiwaki
# たくさん 追加
#
# Revision 1.176  1998/04/10  02:01:50  yoshida
# マロン子供時代追加
#
# Revision 1.175  1998/04/09  03:05:41  takahata
# *** empty log message ***
#
# Revision 1.174  1998/04/08  06:14:51  takahata
# *** empty log message ***
#
# Revision 1.173  1998/04/08  02:34:48  nisiwaki
# リンクのCI化
#
# Revision 1.172  1998/04/07  09:22:54  takahata
# *** empty log message ***
#
# Revision 1.171  1998/04/07  02:20:53  kuzuhara
# アヌビス作成
#
# Revision 1.170  1998/04/06  11:43:31  tarukado
# *** empty log message ***
#
# Revision 1.169  1998/04/06  09:35:20  kuzuhara
# 削除俺様大妖精
#
# Revision 1.168  1998/04/06  07:03:40  sumiyosi
# ライクライク＆妖精の像を追加。
#
# Revision 1.167  1998/04/06  03:16:03  morita
# tw.o
#
# Revision 1.166  1998/04/06  01:37:13  kuzuhara
# 大妖精追加
#
# Revision 1.165  1998/04/04  10:58:09  matutani
# レース馬
#
# Revision 1.164  1998/04/03  02:38:04  takahata
# *** empty log message ***
#
# Revision 1.163  1998/04/01  00:50:54  yoshida
# *** empty log message ***
#
# Revision 1.162  1998/03/27  04:25:47  takahata
# *** empty log message ***
#
# Revision 1.161  1998/03/27  04:20:40  sumiyosi
# シェアード版ゴロン追加。
#
# Revision 1.160  1998/03/26  05:50:12  takahata
# *** empty log message ***
#
# Revision 1.159  1998/03/26  01:58:44  umemiya
# *** empty log message ***
#
# Revision 1.158  1998/03/25  14:00:03  umemiya
# 氷の洞窟、SPOT06オブジェクトなど追加
#
# Revision 1.157  1998/03/25  11:45:51  sumiyosi
# デクの樹Ｊｒ．追加。
#
# Revision 1.156  1998/03/25  09:53:46  takahata
# *** empty log message ***
#
# Revision 1.155  1998/03/25  03:00:43  komatu
# *** empty log message ***
#
# Revision 1.154  1998/03/24  04:06:57  komatu
# *** empty log message ***
#
# Revision 1.153  1998/03/23  09:33:41  takahata
# *** empty log message ***
#
# Revision 1.152  1998/03/23  09:29:04  sakakibara
# *** empty log message ***
#
# Revision 1.151  1998/03/23  06:04:29  takahata
# *** empty log message ***
#
# Revision 1.150  1998/03/21  06:43:33  sumiyosi
# 村人シェアード実験追加。
#
# Revision 1.149  1998/03/19  06:39:39  sakakibara
# Spot16 obj 追加
#
# Revision 1.148  1998/03/19  03:07:55  nisiwaki
# Tr.o を 追加
#
# Revision 1.147  1998/03/18  13:46:47  yoshida
# インゴー追加
#
# Revision 1.146  1998/03/17  10:40:59  takahata
# *** empty log message ***
#
# Revision 1.145  1998/03/16  05:25:59  takahata
# *** empty log message ***
#
# Revision 1.144  1998/03/16  04:58:24  komatu
# *** empty log message ***
#
# Revision 1.143  1998/03/13  10:56:27  takahata
# *** empty log message ***
#
# Revision 1.142  1998/03/13  06:32:29  takahata
# *** empty log message ***
#
# Revision 1.141  1998/03/12  12:29:10  takahata
# *** empty log message ***
#
# Revision 1.140  1998/03/11  10:04:31  takahata
# *** empty log message ***
#
# Revision 1.139  1998/03/10  12:54:28  morita
# mo
#
# Revision 1.138  1998/03/10  04:30:54  komatu
# *** empty log message ***
#
# Revision 1.137  1998/03/09  06:17:11  sakakibara
# *** empty log message ***
#
# Revision 1.136  1998/03/09  04:51:54  takahata
# *** empty log message ***
#
# Revision 1.135  1998/03/06  04:34:17  tarukado
# *** empty log message ***
#
# Revision 1.134  1998/03/04  14:00:32  yoshida
# *** empty log message ***
#
# Revision 1.133  1998/03/04  09:55:07  okajima
# *** empty log message ***
#
# Revision 1.132  1998/03/04  09:34:58  sakakibara
# *** empty log message ***
#
# Revision 1.131  1998/03/04  08:12:12  takahata
# *** empty log message ***
#
# Revision 1.130  1998/03/04  08:11:45  takahata
# *** empty log message ***
#
# Revision 1.129  1998/03/04  06:36:47  nisiwaki
# *** empty log message ***
#
# Revision 1.128  1998/03/03  14:07:27  yoshida
# *** empty log message ***
#
# Revision 1.127  1998/03/03  13:40:37  umemiya
# ブロッブ追加
#
# Revision 1.126  1998/03/03  12:45:20  umemiya
# Warningのため名前変更
#
# Revision 1.125  1998/03/03  08:38:32  nisiwaki
# *** empty log message ***
#
# Revision 1.124  1998/03/03  07:34:53  tarukado
# *** empty log message ***
#
# Revision 1.123  1998/03/02  02:09:01  umemiya
# 墓下ダンジョン・オブジェ追加
#
# Revision 1.122  1998/02/25  13:38:29  matutani
# *** empty log message ***
#
# Revision 1.121  1998/02/24  04:23:45  nisiwaki
# *** empty log message ***
#
# Revision 1.120  1998/02/21  10:41:37  tarukado
# *** empty log message ***
#
# Revision 1.119  1998/02/21  09:21:29  morita
# *** empty log message ***
#
# Revision 1.118  1998/02/20  12:40:12  umemiya
# 燭台をバンクに設定
#
# Revision 1.117  1998/02/20  07:50:43  matutani
# 魔法（炎、風、氷）
#
# Revision 1.116  1998/02/20  02:17:44  umemiya
# スポット０２オブジェクト、墓追加
#
# Revision 1.115  1998/02/19  07:32:25  nisiwaki
# ru1 を 追加
#
# Revision 1.114  1998/02/18  02:43:56  matutani
# 子馬追加
#
# Revision 1.113  1998/02/17  02:26:46  nisiwaki
# *** empty log message ***
#
# Revision 1.112  1998/02/16  09:05:52  sumiyosi
# フレイムダンサーを追加。
#
# Revision 1.111  1998/02/14  13:43:35  iwawaki
# *** empty log message ***
#
# Revision 1.110  1998/02/12  07:04:06  nisiwaki
# *** empty log message ***
#
# Revision 1.109  1998/02/12  02:43:54  morita
# fd追加
#
# Revision 1.108  1998/02/03  07:06:47  tarukado
# ガノン と ファントムガノンを分たっス！！
#
# Revision 1.107  1998/01/31  12:12:20  iwawaki
# *** empty log message ***
#
# Revision 1.106  1998/01/30  02:59:57  umemiya
# ポウ四姉妹追加
#
# Revision 1.105  1998/01/29  09:53:05  tarukado
# *** empty log message ***
#
# Revision 1.104  1998/01/29  07:58:52  tarukado
# *** empty log message ***
#
# Revision 1.103  1998/01/28  04:30:33  tarukado
# *** empty log message ***
#
# Revision 1.102  1998/01/27  07:00:42  umemiya
# 巨大魚ダンジョン・オブジェ追加
#
# Revision 1.101  1998/01/26  10:26:26  iwawaki
# 今寺町です
#
# Revision 1.100  1998/01/26  09:36:53  nisiwaki
# デモ用データ追加
#
# Revision 1.99  1998/01/22  12:02:35  umemiya
# 炎の輪追加
#
# Revision 1.98  1998/01/22  07:30:16  iwawaki
# *** empty log message ***
#
# Revision 1.97  1998/01/20  11:30:31  tarukado
# *** empty log message ***
#
# Revision 1.96  1998/01/20  10:34:14  tarukado
# *** empty log message ***
#
# Revision 1.95  1998/01/20  08:02:15  sumiyosi
# *** empty log message ***
#
# Revision 1.94  1998/01/19  12:34:08  umemiya
# オクタロックのデータを新規に変更
#
# Revision 1.93  1998/01/19  06:39:13  tarukado
# *** empty log message ***
#
# Revision 1.92  1998/01/14  05:51:46  tarukado
# *** empty log message ***
#
# Revision 1.91  1998/01/14  02:37:00  tarukado
# *** empty log message ***
#
# Revision 1.90  1998/01/13  14:11:20  iwawaki
# *** empty log message ***
#
# Revision 1.89  1998/01/12  14:08:35  iwawaki
# *** empty log message ***
#
# Revision 1.88  1998/01/08  10:46:44  umemiya
# 森の神殿、炎の神殿テクスチャ追加
#
# Revision 1.87  1998/01/07  06:09:59  sakakibara
# *** empty log message ***
#
# Revision 1.86  1998/01/05  05:09:33  iwawaki
# *** empty log message ***
#
# Revision 1.85  1997/12/24  06:34:10  sumiyosi
# 大ゼルダ追加
#
# Revision 1.84  1997/12/24  05:06:09  umemiya
# トラップ床ビュン追加
#
# Revision 1.83  1997/12/18  07:54:39  umemiya
# 時の間・オブジェ追加
#
# Revision 1.82  1997/12/18  06:07:05  umemiya
# *** empty log message ***
#
# Revision 1.81  1997/12/18  04:10:51  umemiya
# *** empty log message ***
#
# Revision 1.80  1997/12/17  07:03:14  tarukado
# *** empty log message ***
#
# Revision 1.79  1997/12/17  04:57:10  umemiya
# 森の神殿・ひねり回廊部屋追加
#
# Revision 1.78  1997/12/16  05:59:21  sumiyosi
# *** empty log message ***
#
# Revision 1.77  1997/12/16  00:54:29  matutani
# ファントムガノン馬
#
# Revision 1.76  1997/12/12  02:10:36  tarukado
# *** empty log message ***
#
# Revision 1.75  1997/12/12  01:52:00  tarukado
# *** empty log message ***
#
# Revision 1.74  1997/12/11  06:57:27  tarukado
# *** empty log message ***
#
# Revision 1.73  1997/12/04  09:42:29  umemiya
# 水の神殿・MOVEBGオブジェ追加
#
# Revision 1.72  1997/11/28  00:46:28  sumiyosi
# *** empty log message ***
#
# Revision 1.71  1997/11/26  07:33:26  umemiya
# バリ追加
#
# Revision 1.70  1997/11/18  04:46:20  sumiyosi
# *** empty log message ***
#
# Revision 1.69  1997/11/14  07:32:49  sumiyosi
# コキリ族軍団追加
#
# Revision 1.68  1997/11/12  08:21:34  umemiya
# 面クリダンジョンオブジェクト追加
#
# Revision 1.67  1997/11/12  07:03:41  sumiyosi
# *** empty log message ***
#
# Revision 1.66  1997/11/08  08:37:53  umemiya
# デクナッツ追加
#
# Revision 1.65  1997/11/07  04:05:52  iwawaki
# *** empty log message ***
#
# Revision 1.64  1997/10/25  05:44:13  iwawaki
# *** empty log message ***
#
# Revision 1.63  1997/10/21  09:14:32  matutani
# ゼルダ馬
#
# Revision 1.62  1997/10/20  10:45:48  sumiyosi
# ハイリア住民さらに追加。
#
# Revision 1.61  1997/10/19  09:03:22  iwawaki
# *** empty log message ***
#
# Revision 1.60  1997/10/17  08:26:27  sumiyosi
# ハイリアの住民追加。
#
# Revision 1.59  1997/10/16  08:44:16  sumiyosi
# En_GirlB→子ゼルダに変更。
#
# Revision 1.58  1997/10/08  14:18:04  sumiyosi
# インパ（マスク付）追加
#
# Revision 1.57  1997/10/08  02:28:05  sumiyosi
# ゴロン族追加
#
# Revision 1.56  1997/10/02  13:44:58  umemiya
# *** empty log message ***
#
# Revision 1.55  1997/10/02  12:40:30  umemiya
# デクババ追加
#
# Revision 1.54  1997/10/01  04:31:43  tarukado
# がノンドロフ ＆ アモス 追加
#
# Revision 1.53  1997/10/01  02:37:59  umemiya
# *** empty log message ***
#
# Revision 1.52  1997/10/01  02:26:14  hayakawa
# 日付比較コピー
#
# Revision 1.51  1997/09/29  11:50:51  umemiya
# 妖精ダンジョンオブジェ追加
#
# Revision 1.50  1997/09/29  10:54:54  sumiyosi
# コキリ族の女の子追加
#
# Revision 1.49  1997/09/27  02:05:28  hayakawa
# set -xをコメントアウトした
#
# Revision 1.48  1997/09/26  06:32:40  sumiyosi
# *** empty log message ***
#
# Revision 1.47  1997/09/24  07:30:46  tarukado
# *** empty log message ***
#
# Revision 1.46  1997/09/20  04:16:41  tarukado
# *** empty log message ***
#
# Revision 1.45  1997/09/19  08:57:12  tarukado
# *** empty log message ***
#
# Revision 1.44  1997/09/19  05:29:29  tarukado
# モリブリン追加
#
# Revision 1.43  1997/09/17  13:51:39  umemiya
# spot00オブジェ追加
#
# Revision 1.42  1997/09/17  07:24:54  sumiyosi
# *** empty log message ***
#
# Revision 1.41  1997/09/16  08:47:02  sumiyosi
# *** empty log message ***
#
# Revision 1.40  1997/09/12  12:29:05  matutani
# ガノン馬追加
#
# Revision 1.39  1997/09/11  06:45:09  umemiya
# 火の神殿オブジェ追加
#
# Revision 1.38  1997/09/09  11:54:28  iwawaki
# *** empty log message ***
#
# Revision 1.37  1997/09/05  06:37:10  sumiyosi
# *** empty log message ***
#
# Revision 1.36  1997/09/05  06:35:29  matutani
# *** empty log message ***
#
# Revision 1.35  1997/09/01  02:13:16  tarukado
# *** empty log message ***
#
# Revision 1.34  1997/09/01  01:03:48  tarukado
# *** empty log message ***
#
# Revision 1.33  1997/08/27  11:30:37  sumiyosi
# *** empty log message ***
#
# Revision 1.32  1997/08/27  06:05:06  sumiyosi
# *** empty log message ***
#
# Revision 1.31  1997/08/25  13:37:44  sumiyosi
# スタルチュラ追加。
#
# Revision 1.30  1997/08/25  01:51:32  sumiyosi
# *** empty log message ***
#
# Revision 1.29  1997/08/25  01:49:30  sumiyosi
# *** empty log message ***
#
# Revision 1.28  1997/08/25  01:48:38  hayakawa
# *** empty log message ***
#
# Revision 1.27  1997/08/19  09:46:25  tarukado
# *** empty log message ***
#
# Revision 1.26  1997/08/12  11:11:00  iwawaki
# *** empty log message ***
#
# Revision 1.25  1997/08/05  09:29:58  tarukado
# *** empty log message ***
#
# Revision 1.24  1997/08/04  02:38:22  iwawaki
# *** empty log message ***
#
# Revision 1.23  1997/07/30  01:25:20  tarukado
# *** empty log message ***
#
# Revision 1.22  1997/07/18  11:24:31  tarukado
# *** empty log message ***
#
# Revision 1.21  1997/07/18  01:16:01  tarukado
# *** empty log message ***
#
# Revision 1.20  1997/07/17  09:49:45  iwawaki
# *** empty log message ***
#
# Revision 1.19  1997/07/17  08:39:26  tarukado
# *** empty log message ***
#
# Revision 1.18  1997/07/17  06:25:26  tarukado
# *** empty log message ***
#
# Revision 1.17  1997/07/17  06:08:48  tarukado
# *** empty log message ***
#
# Revision 1.16  1997/07/17  02:50:13  tarukado
# *** empty log message ***
#
# Revision 1.15  1997/07/17  02:49:41  tarukado
# *** empty log message ***
#
# Revision 1.14  1997/07/17  02:35:34  tarukado
# *** empty log message ***
#
# Revision 1.13  1997/07/17  01:46:25  tarukado
# *** empty log message ***
#
# Revision 1.12  1997/07/09  08:37:57  sumiyosi
# *** empty log message ***
#
# Revision 1.11  1997/07/09  07:22:03  iwawaki
# *** empty log message ***
#
# Revision 1.10  1997/07/02  09:03:44  tarukado
# *** empty log message ***
#
# Revision 1.9  1997/07/02  08:04:50  tarukado
# *** empty log message ***
#
# Revision 1.8  1997/06/26  12:33:43  iwawaki
# *** empty log message ***
#
# Revision 1.7  1997/06/19  00:42:49  iwawaki
# *** empty log message ***
#
# Revision 1.6  1997/06/06  06:57:42  iwawaki
# *** empty log message ***
#
# Revision 1.5  1997/06/06  05:48:25  iwawaki
# *** empty log message ***
#
# Revision 1.4  1997/06/05  07:49:04  iwawaki
# *** empty log message ***
#
# Revision 1.3  1997/06/05  07:18:12  iwawaki
# *** empty log message ***
#
# Revision 1.2  1997/05/26  10:26:49  iwawaki
# *** empty log message ***
#
# Revision 1.1  1997/05/26  06:37:52  iwawaki
# Initial revision
#

cp2() {
  if [ ! -e $2 -o $1 -nt $2 ]; then
    echo    cp $1 $2
    command cp $1 $2
  fi
}
cp() {
  SRC=$1
  DEST=$2
  SRCBASE=`basename $SRC`
  if [ -d $DEST ]; then
    cp2 $SRC $DEST/$SRCBASE
  else
    cp2 $SRC $DEST
  fi
}

     cp shape/zelda2_field_keep/zelda2_field_keep.o Field_keep.o
     cp shape/zelda2_dangeon_keep/zelda2_dangeon_keep.o Dangeon_keep.o
     cp shape/zelda2_link_new/Anime_Data/Anime_Data.o Link_anime_data.o

#     cp shape/zelda_link_ci/Boy/Boy.o Link_boy.o
#     cp shape/zelda_link_ci/Child/Child.o Link_child.o

#     cp shape/zelda2_link_new/Skeleton/Boy/Boy.o Link_boy.o
     cp shape/zelda2_link_new/Skeleton/Boy2/Boy2.o Link_boy.o
     cp shape/zelda2_link_new/Skeleton/Child3/Child3.o Link_child.o
     cp shape/zelda2_link_new/Skeleton/Goron/Goron.o Link_goron.o
     cp shape/zelda2_link_new/Skeleton/Zora/Zora.o Link_zora.o
     cp shape/zelda2_link_new/Skeleton/Nuts/Nuts.o Link_nuts.o
     cp shape/zelda2_link_new/Skeleton/Mask/Geld/Geld.o Link_mask_geld.o
     cp shape/zelda2_link_new/Skeleton/Mask/Ki_tan/Ki_tan.o Link_mask_ki_tan.o
     cp shape/zelda2_link_new/Skeleton/Mask/Rabit/Rabit.o Link_mask_rabit.o
     cp shape/zelda2_link_new/Skeleton/Mask/Redead/Redead.o Link_mask_redead.o
     cp shape/zelda2_link_new/Skeleton/Mask/Skj/Skj.o Link_mask_skj.o
     cp shape/zelda2_link_new/Skeleton/Mask/Truth/Truth.o Link_mask_truth.o
     cp shape/zelda2_link_new/Skeleton/Mask/Gibudo/Gibudo.o Link_mask_gibudo.o
     cp shape/zelda2_link_new/Skeleton/Mask/Json/Json.o Link_mask_json.o
     cp shape/zelda2_link_new/Skeleton/Mask/Kerfay/Kerfay.o Link_mask_kerfay.o
     cp shape/zelda2_link_new/Skeleton/Mask/Bigelf/Bigelf.o Link_mask_bigelf.o
     cp shape/zelda2_link_new/Skeleton/Mask/Kyojin/Kyojin.o Link_mask_kyojin.o
     cp shape/zelda2_link_new/Skeleton/Mask/Romerny/Romerny.o Link_mask_romerny.o
     cp shape/zelda2_link_new/Skeleton/Mask/Goron/Goron.o Link_mask_goron.o
     cp shape/zelda2_link_new/Skeleton/Mask/Zora/Zora.o Link_mask_zora.o
     cp shape/zelda2_link_new/Skeleton/Mask/Nuts/Nuts.o Link_mask_nuts.o
     cp shape/zelda2_link_new/Skeleton/Mask/Boy/Boy.o Link_mask_boy.o

#     cp /home/nisiwaki/ZELDA/LINK/Boy/Boy.o Link_boy.o
#     cp /home/nisiwaki/ZELDA/LINK/Child/Child.o Link_child.o

#     cp /home/yoshida/gamegen/cnv/LINK/main/Boy/Boy.o Link_boy.o
#     cp /home/yoshida/gamegen/cnv/LINK/main/Child/Child.o Link_child.o

#     cp shape/zelda_box/zelda_box.o Box.o
     cp shape/zelda2_box/zelda2_box.o Box.o
     cp shape/zelda_dodongo/zelda_dodongo.o Dodongo.o
#     cp shape/zelda_fire/zelda_fire.o Fire.o
#     cp shape/zelda_human/zelda_human.o Human.o
     cp shape/zelda_nw/zelda_nw.o Niw.o
     cp shape/zelda_st/zelda_st.o St.o
     cp shape/zelda_tt/zelda_tt.o Tite.o
#     cp shape/zelda_rb/zelda_rb.o Reeba.o
     cp shape/zelda_ph/zelda_ph.o Peehat.o
     cp shape/zelda_horse/zelda_horse.o Horse.o
#     cp shape/zelda2_zf/zelda2_zf.o Zf.o
#     cp shape/zelda_goma/zelda_goma.o Go.o
#     cp shape/zelda_goma_PAL/zelda_goma_PAL.o Go_PAL.o
#     cp shape/zelda_kdodongo/zelda_kdodongo.o Kdodongo.o
#     cp shape/zelda_kdodongo_PAL/zelda_kdodongo_PAL.o Kdodongo_PAL.o
     cp shape/zelda_zl1/zelda_zl1.o Zl1.o
     cp shape/zelda_ff/zelda_ff.o Ff.o
     cp shape/zelda_wm2/zelda_wm2.o Wm.o
#     cp shape/zelda_oAx/zelda_oAx.o OAX.o
     cp shape/zelda2_oc/zelda2_oc.o Oc.o
     cp shape/zelda_tg2/zelda_tg2.o Tg2.o
#     cp shape/zelda_kogoma/zelda_kogoma.o Gol.o
     cp shape/zelda_bubble/zelda_bubble.o Bubble.o
#     cp shape/zelda_dodojr/zelda_dodojr.o Dodojr.o
     cp shape/zelda_black_link/zelda_black_link.o Torch2.o
#     cp shape/zelda_bl/zelda_bl.o Bl.o
#     cp shape/zelda_tp/zelda_tp.o Tp.o
#     cp shape/zelda_bw/zelda_bw.o Bw.o
#     cp shape/zelda_ei/zelda_ei.o Ei.o
     cp shape/zelda_horse_normal/zelda_horse_normal.o Horse_Normal.o
#     cp shape/zelda_oBx/zelda_oBx.o OBX.o
#     cp shape/zelda_o_anime/zelda_o_anime.o O_anime.o
#     cp shape/zelda_horse_ganon/zelda_horse_ganon.o Horse_Ganon.o
#     cp shape/zelda_oA2/zelda_oA2.o OA2.o
#     cp shape/zelda_spot00_objects/zelda_spot00_objects.o spot00_objects.o
#     cp shape/zelda_mb/zelda_mb.o Mb.o
     cp shape/zelda_bombf/zelda_bombf.o Bombf.o
#     cp shape/zelda_sk2/zelda_sk2.o Sk2.o
#     cp shape/zelda_oE1/zelda_oE1.o OE1.o
#     cp shape/zelda_oE_anime/zelda_oE_anime.o OE_anime.o
#     cp shape/zelda_oE2/zelda_oE2.o OE2.o
#     cp shape/zelda_gnd/zelda_gnd.o Gnd.o
     cp shape/zelda2_am/zelda2_am.o Am.o
     cp shape/zelda_dekubaba/zelda_dekubaba.o Dekubaba.o
#     cp shape/zelda_oA3/zelda_oA3.o OA3.o
#     cp shape/zelda_oA4/zelda_oA4.o OA4.o
#     cp shape/zelda_oA5/zelda_oA5.o OA5.o
#     cp shape/zelda_oA6/zelda_oA6.o OA6.o
#     cp shape/zelda_oA7/zelda_oA7.o OA7.o
#     cp shape/zelda_oA8/zelda_oA8.o OA8.o
#     cp shape/zelda_oA9/zelda_oA9.o OA9.o
#     cp shape/zelda_oB2/zelda_oB2.o OB2.o
#     cp shape/zelda_oB3/zelda_oB3.o OB3.o
#     cp shape/zelda_oB4/zelda_oB4.o OB4.o
#     cp shape/zelda_horse_zelda/zelda_horse_zelda.o Horse_Zelda.o
#     cp shape/zelda_opdemo1/zelda_opdemo1.o Opening_Demo1.o
     cp shape/zelda_warp1/zelda_warp1.o Warp1.o
     cp shape/zelda_b_heart/zelda_b_heart.o B_heart.o
     cp shape/zelda2_dekunuts_new/zelda2_dekunuts_new.o Dekunuts.o
#     cp shape/zelda2_dekunuts/zelda2_dekunuts.o Dekunuts.o
#     cp shape/zelda_oE3/zelda_oE3.o OE3.o
#     cp shape/zelda_oE4/zelda_oE4.o OE4.o
#     cp shape/zelda_menkuri_objects/zelda_menkuri_objects.o menkuri_objects.o
#     cp shape/zelda_oE5/zelda_oE5.o OE5.o
#     cp shape/zelda_oE6/zelda_oE6.o OE6.o
#     cp shape/zelda_oE7/zelda_oE7.o OE7.o
#     cp shape/zelda_oE8/zelda_oE8.o OE8.o
#     cp shape/zelda_oE9/zelda_oE9.o OE9.o
#     cp shape/zelda_oE10/zelda_oE10.o OE10.o
#     cp shape/zelda_oE11/zelda_oE11.o OE11.o
#     cp shape/zelda_oE12/zelda_oE12.o OE12.o
#     cp shape/zelda_vali/zelda_vali.o Vali.o
#     cp shape/zelda_oA10/zelda_oA10.o OA10.o
#     cp shape/zelda_oA11/zelda_oA11.o OA11.o
#     cp shape/zelda_fantomHG/zelda_fantomHG.o FantomHG.o
#     cp shape/zelda_fantomHG_PAL/zelda_fantomHG_PAL.o FantomHG_PAL.o
     cp shape/zelda_sh/zelda_sh.o OB1.o
     cp shape/zelda_bb/zelda_bb.o Bb.o
#     cp shape/zelda_yukabyun/zelda_yukabyun.o Yukabyun.o
#     cp shape/zelda_zl2/zelda_zl2.o Zl2.o
#     cp shape/zelda_mjin/zelda_mjin.o Mjin.o
#     cp shape/zelda_mjin_flash/zelda_mjin_flash.o Flash_mjin.o
#     cp shape/zelda_mjin_dark/zelda_mjin_dark.o Dark_mjin.o
#     cp shape/zelda_mjin_flame/zelda_mjin_flame.o Flame_mjin.o
#     cp shape/zelda_mjin_ice/zelda_mjin_ice.o Ice_mjin.o
#     cp shape/zelda_mjin_soul/zelda_mjin_soul.o Soul_mjin.o
#     cp shape/zelda_mjin_wind/zelda_mjin_wind.o Wind_mjin.o
#     cp shape/zelda_mjin_oka/zelda_mjin_oka.o Oka_mjin.o
#     cp shape/zelda_warp2/zelda_warp2.o Warp2.o
     cp shape/zelda2_hata/zelda2_hata.o Hata.o
#     cp shape/zelda_bird/zelda_bird.o Bird.o
     cp shape/zelda_stree/zelda_stree.o Stree.o
     cp shape/zelda_kui/zelda_kui.o Kui.o
     cp shape/zelda_maruta/zelda_maruta.o Maruta.o
     cp shape/zelda_saku/zelda_saku.o Saku.o
     cp shape/zelda2_wood02/zelda2_wood02.o Wood02.o
     cp shape/zelda_t_wood01/zelda_t_wood01.o Twood01.o
     cp shape/zelda_kabu02/zelda_kabu02.o Kabu02.o
     cp shape/dk_board/dk_board.o Board.o
     cp shape/dk_floater/dk_floater.o Floater.o
#     cp shape/dk_lightbox/dk_lightbox.o Lightbox.o
#     cp shape/dk_pu_box/dk_pu_box.o Pu_box.o
     cp shape/dk_spia/dk_spia.o Spia.o
     cp shape/dk_stonebridge/dk_stonebridge.o Stonebridge.o
     cp shape/dk_trap/dk_trap.o Trap.o
#     cp shape/dk_vase/dk_vase.o Vase.o
#     cp shape/zelda_im/zelda_im.o Im.o
#     cp shape/zelda_xc/zelda_xc.o Xc.o
#     cp shape/zelda_xc_pal/zelda_xc_pal.o Xc_pal.o
     cp shape/zelda2_ta/zelda2_ta.o Ta.o
#     cp shape/zelda_tk/zelda_tk.o Tk.o
     cp shape/zelda_vm/zelda_vm.o Vm.o
#     cp shape/zelda_bv/zelda_bv.o Bv.o
#     cp shape/zelda_bv_PAL/zelda_bv_PAL.o Bv_PAL.o
#     cp shape/zelda_efc_crystal_light/zelda_efc_crystal_light.o  efc_crystal_light.o
#    cp shape/zelda_efc_fire_ball/zelda_efc_fire_ball.o  efc_fire_ball.o
#    cp shape/zelda2_flash/zelda2_flash.o Flash.o
#    cp shape/zelda_efc_lgt_shower/zelda_efc_lgt_shower.o   efc_lgt_shower.o
     cp shape/zelda_efc_star_field/zelda_efc_star_field.o   efc_star_field.o
#    cp shape/zelda_god_lgt/zelda_god_lgt.o god_lgt.o   
#    cp shape/zelda_light_ring/zelda_light_ring.o light_ring.o   
#    cp shape/zelda_triforce_spot/zelda_triforce_spot.o  triforce_spot.o
     cp shape/zelda_sd/zelda_sd.o Sd.o
     cp shape/zelda2_rd/zelda2_rd.o Rd.o
     cp shape/zelda_po_sisters/zelda_po_sisters.o Po_Sisters.o
     cp shape/zelda_heavy_object/zelda_heavy_object.o Heavy_object.o
#     cp shape/zelda_gndd/zelda_gndd.o Gndd.o
#     cp shape/zelda_fd/zelda_fd.o fd.o
#     cp shape/zelda_fd_PAL/zelda_fd_PAL.o fd_PAL.o
#     cp shape/zelda_du/zelda_du.o du.o
#     cp shape/zelda_du_PAL/zelda_du_PAL.o du_PAL.o
#     cp shape/zelda_fw/zelda_fw.o fw.o
#     cp shape/zelda_medal/medal.o medal.o
#     cp shape/zelda_hlc/zelda_hlc.o hlc.o
     cp shape/zelda2_hlc/zelda2_hlc.o hlc.o
#     cp shape/zelda_ru1/zelda_ru1.o ru1.o
#     cp shape/zelda_haka/zelda_haka.o Haka.o
     cp shape/zelda_syokudai/zelda_syokudai.o syokudai.o
#     cp shape/zelda_vba/zelda_vba.o fd2.o
     cp shape/zelda_dh/zelda_dh.o Dh.o
     cp shape/zelda_efc_tw/zelda_efc_tw.o efc_tw.o
#     cp shape/zelda_rl/zelda_rl.o Rl.o
#     cp shape/zelda_tre_lgt/zelda_tre_lgt.o demo_tre_lgt.o
#     cp shape/zelda_haka_objects/zelda_haka_objects.o haka_objects.o
     cp shape/zelda_key/zelda_key.o gi_key.o
     cp shape/zelda2_mir_ray/zelda2_mir_ray.o mir_ray.o
     cp shape/zelda2_ctower_rot/zelda2_ctower_rot.o Ctower_Rot.o
#     cp shape/zelda_gi_jewel/zelda_gi_jewel.o gi_jewel.o
     cp shape/zelda2_boss_door/zelda2_boss_door.o bdoor.o
     cp shape/zelda_shop_tana/zelda_shop_tana.o shop_dungen.o
#     cp shape/zelda_nb/zelda_nb.o nb.o
#     cp shape/zelda_mo/zelda_mo.o mo.o
#     cp shape/zelda_mo_PAL/zelda_mo_PAL.o mo_PAL.o
     cp shape/zelda_sb/zelda_sb.o sb.o
     cp shape/zelda_gi_melody/zelda_gi_melody.o gi_melody.o
     cp shape/zelda_gi_heart/zelda_gi_heart.o gi_heart.o
     cp shape/zelda_gi_compass/zelda_gi_compass.o gi_compass.o
     cp shape/zelda_gi_bosskey/zelda_gi_bosskey.o gi_bosskey.o
#     cp shape/zelda_gi_medal/zelda_gi_medal.o gi_medal.o
     cp shape/zelda_gi_nuts/zelda_gi_nuts.o gi_nuts.o
#     cp shape/zelda2_sa/zelda2_sa.o sa.o
     cp shape/zelda_gi_hearts/zelda_gi_hearts.o gi_hearts.o
     cp shape/zelda_gi_arrowcase/zelda_gi_arrowcase.o gi_arrowcase.o
     cp shape/zelda_gi_bombpouch/zelda_gi_bombpouch.o gi_bombpouch.o
#     cp shape/zelda_in/zelda_in.o In.o
     cp shape/zelda2_in/zelda2_in.o In.o
#     cp shape/zelda2_tr/zelda2_tr.o Tr.o
#     cp shape/zelda_oE1s/zelda_oE1s.o oE1s.o
#     cp shape/zelda_oE4s/zelda_oE4s.o oE4s.o
     cp shape/zelda2_npc_anime/zelda2_npc_anime.o os_anime.o
     cp shape/zelda_gi_bottle/zelda_gi_bottle.o gi_bottle.o
     cp shape/zelda2_dy_obj/zelda2_dy_obj.o dy_obj.o
     cp shape/zelda_gi_stick/zelda_gi_stick.o gi_stick.o
     cp shape/zelda_gi_map/zelda_gi_map.o gi_map.o
     cp shape/zelda2_oF1d/zelda2_oF1d.o oF1d_map.o
     cp shape/zelda_ru2/zelda_ru2.o ru2.o
#     cp shape/zelda_gi_shield_1/zelda_gi_shield_1.o gi_shield_1.o
     cp shape/zelda_dekujr/zelda_dekujr.o dekujr.o
     cp shape/zelda_gi_magicpot/zelda_gi_magicpot.o gi_magicpot.o
     cp shape/zelda_gi_bomb_1/zelda_gi_bomb_1.o gi_bomb_1.o
#     cp shape/zelda_oF1s/zelda_oF1s.o oF1s.o
     cp shape/zelda_ma2/zelda_ma2.o Ma2.o
     cp shape/zelda_gi_purse/zelda_gi_purse.o gi_purse.o
     cp shape/zelda_hni/zelda_hni.o Hni.o
#     cp shape/zelda_tw/zelda_tw.o tw.o
#     cp shape/zelda_tw_PAL/zelda_tw_PAL.o tw_PAL.o
     cp shape/zelda_rr/zelda_rr.o rr.o
#     cp shape/zelda_bxa/zelda_bxa.o bxa.o
#     cp shape/zelda_av/zelda_av.o Av.o
#     cp shape/zelda_gi_gerudo/zelda_gi_gerudo.o gi_gerudo.o
     cp shape/zelda_gi_arrow/zelda_gi_arrow.o gi_arrow.o
     cp shape/zelda_gi_bomb_2/zelda_gi_bomb_2.o gi_bomb_2.o
#     cp shape/zelda_gi_egg/zelda_gi_egg.o gi_egg.o
#     cp shape/zelda_gi_scale/zelda_gi_scale.o gi_scale.o
#	cp shape/zelda_gi_shield_2/zelda_gi_shield_2.o gi_shield_2.o
    cp shape/zelda2_gi_shield_01/v2_shield_01.o gi_shield_2.o
#     cp shape/zelda_gi_hookshot/zelda_gi_hookshot.o gi_hookshot.o
     cp shape/zelda2_gi_hookshot/zelda2_gi_hookshot.o gi_hookshot.o
     cp shape/zelda_gi_ocarina/zelda_gi_ocarina.o gi_ocarina.o
     cp shape/zelda_gi_milk/zelda_gi_milk.o gi_milk.o
     cp shape/zelda2_ma1/zelda2_ma1.o Ma1.o
#     cp shape/zelda_ganon/zelda_ganon.o B_ganon.o
#     cp shape/zelda_ganon_PAL/zelda_ganon_PAL.o B_ganon_PAL.o
#     cp shape/zelda_ganon_anime1/zelda_ganon_anime1.o Ganon_Anime1.o
#     cp shape/zelda_ganon_anime2/zelda_ganon_anime2.o Ganon_Anime2.o
#     cp shape/zelda_ganon_anime3/zelda_ganon_anime3.o Ganon_Anime3.o
#     cp shape/zelda_sst/zelda_sst.o Sst.o
#     cp shape/zelda_sst_PAL/zelda_sst_PAL.o Sst_PAL.o
#     cp shape/zelda_go2/zelda_go2.o Go2.o
     cp shape/zelda_ny/zelda_ny.o Ny.o
     cp shape/zelda2_fr/zelda2_fr.o Fr.o
#     cp shape/zelda_gi_pachinko/zelda_gi_pachinko.o gi_pachinko.o
#     cp shape/zelda_gi_boomerang/zelda_gi_boomerang.o gi_boomerang.o
     cp shape/zelda2_gi_bow/zelda2_gi_bow.o gi_bow.o
     cp shape/zelda_gi_glasses/zelda_gi_glasses.o gi_glasses.o
     cp shape/zelda2_scene_name/G_pn_01/G_pn_01.o .
     cp shape/zelda_scene_name2/G_pn_02/G_pn_02.o .
     cp shape/zelda_scene_name2/G_pn_03/G_pn_03.o .
     cp shape/zelda_scene_name2/G_pn_04/G_pn_04.o .
     cp shape/zelda_scene_name2/G_pn_05/G_pn_05.o .
     cp shape/zelda_scene_name2/G_pn_06/G_pn_06.o .
     cp shape/zelda_scene_name2/G_pn_07/G_pn_07.o .
     cp shape/zelda_scene_name2/G_pn_08/G_pn_08.o .
     cp shape/zelda_scene_name2/G_pn_09/G_pn_09.o .
     cp shape/zelda_scene_name2/G_pn_10/G_pn_10.o .
     cp shape/zelda_scene_name2/G_pn_11/G_pn_11.o .
     cp shape/zelda_scene_name2/G_pn_12/G_pn_12.o .
     cp shape/zelda_scene_name2/G_pn_13/G_pn_13.o .
     cp shape/zelda_scene_name2/G_pn_14/G_pn_14.o .
     cp shape/zelda_scene_name2/G_pn_15/G_pn_15.o .
     cp shape/zelda_scene_name2/G_pn_16/G_pn_16.o .
     cp shape/zelda_scene_name2/G_pn_17/G_pn_17.o .
     cp shape/zelda_scene_name2/G_pn_18/G_pn_18.o .
     cp shape/zelda_scene_name2/G_pn_19/G_pn_19.o .
     cp shape/zelda_scene_name2/G_pn_20/G_pn_20.o .
     cp shape/zelda_scene_name2/G_pn_21/G_pn_21.o .
     cp shape/zelda_scene_name2/G_pn_22/G_pn_22.o .
     cp shape/zelda_scene_name2/G_pn_23/G_pn_23.o .
     cp shape/zelda_scene_name2/G_pn_24/G_pn_24.o .
     cp shape/zelda_scene_name2/G_pn_25/G_pn_25.o .
     cp shape/zelda_scene_name2/G_pn_26/G_pn_26.o .
     cp shape/zelda_scene_name2/G_pn_27/G_pn_27.o .
     cp shape/zelda_scene_name2/G_pn_28/G_pn_28.o .
     cp shape/zelda_scene_name2/G_pn_29/G_pn_29.o .
     cp shape/zelda_scene_name2/G_pn_30/G_pn_30.o .
     cp shape/zelda_scene_name2/G_pn_31/G_pn_31.o .
     cp shape/zelda_scene_name2/G_pn_32/G_pn_32.o .
     cp shape/zelda_scene_name2/G_pn_33/G_pn_33.o .
     cp shape/zelda_scene_name2/G_pn_34/G_pn_34.o .
     cp shape/zelda_scene_name2/G_pn_35/G_pn_35.o .
     cp shape/zelda_scene_name2/G_pn_36/G_pn_36.o .
     cp shape/zelda_scene_name2/G_pn_37/G_pn_37.o .
     cp shape/zelda_scene_name2/G_pn_38/G_pn_38.o .
     cp shape/zelda_scene_name2/G_pn_39/G_pn_39.o .
     cp shape/zelda_scene_name2/G_pn_40/G_pn_40.o .
     cp shape/zelda_scene_name2/G_pn_41/G_pn_41.o .
     cp shape/zelda_scene_name2/G_pn_42/G_pn_42.o .
     cp shape/zelda_scene_name2/G_pn_43/G_pn_43.o .
     cp shape/zelda_scene_name2/G_pn_44/G_pn_44.o .
     cp shape/zelda_scene_name2/G_pn_45/G_pn_45.o .
     cp shape/zelda_scene_name2/G_pn_46/G_pn_46.o .
     cp shape/zelda_scene_name2/G_pn_47/G_pn_47.o .
     cp shape/zelda_scene_name2/G_pn_48/G_pn_48.o .
     cp shape/zelda_scene_name2/G_pn_49/G_pn_49.o .
     cp shape/zelda_scene_name2/G_pn_50/G_pn_50.o .
     cp shape/zelda_scene_name2/G_pn_51/G_pn_51.o .
     cp shape/zelda_scene_name2/G_pn_52/G_pn_52.o .
     cp shape/zelda_scene_name2/G_pn_53/G_pn_53.o .
     cp shape/zelda_scene_name2/G_pn_54/G_pn_54.o .
     cp shape/zelda_scene_name2/G_pn_55/G_pn_55.o .
     cp shape/zelda_scene_name2/G_pn_56/G_pn_56.o .
     cp shape/zelda_scene_name2/G_pn_57/G_pn_57.o .
     cp shape/zelda_scene_name_PAL/G_pn_01/G_pn_01.o G_pn_01_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_02/G_pn_02.o G_pn_02_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_03/G_pn_03.o G_pn_03_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_04/G_pn_04.o G_pn_04_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_05/G_pn_05.o G_pn_05_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_06/G_pn_06.o G_pn_06_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_07/G_pn_07.o G_pn_07_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_08/G_pn_08.o G_pn_08_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_09/G_pn_09.o G_pn_09_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_10/G_pn_10.o G_pn_10_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_11/G_pn_11.o G_pn_11_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_12/G_pn_12.o G_pn_12_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_13/G_pn_13.o G_pn_13_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_14/G_pn_14.o G_pn_14_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_15/G_pn_15.o G_pn_15_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_16/G_pn_16.o G_pn_16_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_17/G_pn_17.o G_pn_17_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_18/G_pn_18.o G_pn_18_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_19/G_pn_19.o G_pn_19_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_20/G_pn_20.o G_pn_20_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_21/G_pn_21.o G_pn_21_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_22/G_pn_22.o G_pn_22_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_23/G_pn_23.o G_pn_23_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_24/G_pn_24.o G_pn_24_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_25/G_pn_25.o G_pn_25_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_26/G_pn_26.o G_pn_26_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_27/G_pn_27.o G_pn_27_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_28/G_pn_28.o G_pn_28_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_29/G_pn_29.o G_pn_29_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_30/G_pn_30.o G_pn_30_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_31/G_pn_31.o G_pn_31_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_32/G_pn_32.o G_pn_32_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_33/G_pn_33.o G_pn_33_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_34/G_pn_34.o G_pn_34_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_35/G_pn_35.o G_pn_35_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_36/G_pn_36.o G_pn_36_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_37/G_pn_37.o G_pn_37_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_38/G_pn_38.o G_pn_38_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_39/G_pn_39.o G_pn_39_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_40/G_pn_40.o G_pn_40_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_41/G_pn_41.o G_pn_41_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_42/G_pn_42.o G_pn_42_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_43/G_pn_43.o G_pn_43_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_44/G_pn_44.o G_pn_44_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_45/G_pn_45.o G_pn_45_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_46/G_pn_46.o G_pn_46_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_47/G_pn_47.o G_pn_47_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_48/G_pn_48.o G_pn_48_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_49/G_pn_49.o G_pn_49_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_50/G_pn_50.o G_pn_50_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_51/G_pn_51.o G_pn_51_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_52/G_pn_52.o G_pn_52_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_53/G_pn_53.o G_pn_53_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_54/G_pn_54.o G_pn_54_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_55/G_pn_55.o G_pn_55_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_56/G_pn_56.o G_pn_56_PAL.o
     cp shape/zelda_scene_name_PAL/G_pn_57/G_pn_57.o G_pn_57_PAL.o
     cp shape/zelda_gi_liquid/zelda_gi_liquid.o gi_liquid.o
     cp shape/zelda2_ani/zelda2_ani.o ani.o
#     cp shape/zelda_gi_shield_3/zelda_gi_shield_3.o gi_shield_3.o
     cp shape/zelda2_gi_shield_02/zelda2_gi_shield_02.o gi_shield_3.o
#     cp shape/zelda_gi_letter/zelda_gi_letter.o gi_letter.o
#     cp shape/zelda_gi_clothes/zelda_gi_clothes.o gi_clothes.o
     cp shape/zelda_gi_bean/zelda_gi_bean.o gi_bean.o
     cp shape/zelda_gi_fish/zelda_gi_fish.o gi_fish.o
#     cp shape/zelda_gi_saw/zelda_gi_saw.o gi_saw.o
     cp shape/zelda_gi_hammer/zelda_gi_hammer.o gi_hammer.o
#     cp shape/zelda_gi_grass/zelda_gi_grass.o gi_grass.o
     cp shape/zelda_gi_longsword/zelda_gi_longsword.o gi_longsword.o
#     cp shape/zelda_gate/zelda_gate.o Gate.o
#     cp shape/zelda2_md/zelda2_md.o Md.o
     cp shape/zelda_km1/zelda_km1.o Km1.o
#     cp shape/zelda_kw1/zelda_kw1.o Kw1.o
     cp shape/zelda_zo/zelda_zo.o Zo.o
#     cp shape/zelda_kz/zelda_kz.o Kz.o
     cp shape/zelda_umajump/zelda_umajump.o Umajump.o
     cp shape/zelda_masterkokiri/zelda_masterkokiri.o masterkokiri.o
     cp shape/zelda_masterkokirihead/zelda_masterkokirihead.o masterkokirihead.o
     cp shape/zelda_mastergolon/zelda_mastergolon.o mastergolon.o
     cp shape/zelda_masterzoora/zelda_masterzoora.o masterzoora.o
     cp shape/zelda_aob/zelda_aob.o Aob.o
     cp shape/zelda2_ik/zelda2_ik.o Ik.o
     cp shape/zelda_ahg/zelda_ahg.o Ahg.o
     cp shape/zelda_cne/zelda_cne.o Cne.o
#     cp shape/zelda_gi_chicken/zelda_gi_chicken.o gi_niwatori.o
#     cp shape/zelda2_skj/zelda2_skj.o Skj.o
#     cp shape/zelda_gi_bottle_letter/zelda_gi_bottle_letter.o gi_bottle_letter.o
#     cp shape/zelda_bji/zelda_bji.o Bji.o
     cp shape/zelda_bba/zelda_bba.o Bba.o
#     cp shape/zelda_gi_ocarina_0/zelda_gi_ocarina_0.o gi_ocarina_0.o
     cp shape/zelda_ds/zelda_ds.o Ds.o
     cp shape/zelda_ane/zelda_ane.o Ane.o
     cp shape/zelda2_boj/zelda2_boj.o Boj.o
     cp shape/zelda_elf_message/field/field.o EM_field.o
     cp shape/zelda_elf_message/ydan/ydan.o EM_ydan.o
     cp shape/zelda_fz/zelda_fz.o Fz.o
     cp shape/zelda_bob/zelda_bob.o Bob.o
     cp shape/zelda2_ge1/zelda2_ge1.o Ge1.o
     cp shape/zelda_yabusame_point/zelda_yabusame_point.o yabusame_point.o
#     cp shape/zelda_gi_boots_2/zelda_gi_boots_2.o gi_boots_2.o
#     cp shape/zelda_gi_seed/zelda_gi_seed.o gi_seed.o
#     cp shape/zelda_gnd_magic/zelda_gnd_magic.o gnd_magic.o
#     cp shape/zelda_d_elevator/zelda_d_elevator.o d_elevator.o
     cp shape/zelda_d_hsblock/zelda_d_hsblock.o d_hsblock.o
     cp shape/zelda2_d_lift/zelda2_d_lift.o d_lift.o
     cp shape/zelda2_mamenoki/zelda2_mamenoki.o mamenoki.o
     cp shape/zelda2_goroiwa/zelda2_goroiwa.o goroiwa.o
     cp shape/zelda2_toryo/zelda2_toryo.o toryo.o
     cp shape/zelda_daiku/zelda_daiku.o daiku.o
     cp shape/zelda_stopge/zelda_stopge.o stopge.o
     cp shape/zelda2_nwc/zelda2_nwc.o nwc.o
     cp shape/zelda_hakach_objects/zelda_hakach_objects.o hakach_objects.o
     cp shape/zelda2_gm/zelda2_gm.o gm.o
     cp shape/zelda_ms/zelda_ms.o ms.o
     cp shape/zelda_hs/zelda_hs.o hs.o
#     cp shape/zelda_ingate/zelda_ingate.o Ingate.o
     cp shape/zelda_lightswitch/zelda_lightswitch.o lightswitch.o
     cp shape/zelda_kusa/zelda_kusa.o kusa.o
     cp shape/zelda_tsubo/zelda_tsubo.o tsubo.o
#     cp shape/zelda_gi_gloves/zelda_gi_gloves.o gi_gloves.o
#     cp shape/zelda_gi_coin/zelda_gi_coin.o gi_coin.o
     cp shape/zelda_kanban/zelda_kanban.o kanban.o
     cp shape/zelda_gjyo_objects/zelda_gjyo_objects.o Gjyo_objects.o
     cp shape/zelda2_owl/zelda2_owl.o Owl.o
     cp shape/zelda2_mk/zelda2_mk.o Mk.o
     cp shape/zelda_fu/zelda_fu.o Fu.o
     cp shape/zelda_gi_ki_tan_mask/zelda_gi_ki_tan_mask.o gi_ki_tan_mask.o 
     cp shape/zelda_gi_redead_mask/zelda_gi_redead_mask.o gi_redead_mask.o
     cp shape/zelda_gi_skj_mask/zelda_gi_skj_mask.o gi_skj_mask.o
     cp shape/zelda_gi_rabit_mask/zelda_gi_rabit_mask.o gi_rabit_mask.o
     cp shape/zelda_gi_truth_mask/zelda_gi_truth_mask.o gi_truth_mask.o
     cp shape/zelda_siofuki/zelda_siofuki.o siofuki.o
     cp shape/zelda_stream/zelda_stream.o stream.o
     cp shape/zelda2_mm/zelda2_mm.o mm.o
#     cp shape/zelda_fa/zelda_fa.o fa.o
     cp shape/zelda_os/zelda_os.o os.o
#     cp shape/zelda_gi_eye_lotion/zelda_gi_eye_lotion.o gi_eye_lotion.o
#     cp shape/zelda_gi_powder/zelda_gi_powder.o gi_powder.o
     cp shape/zelda_gi_mushroom/zelda_gi_mushroom.o gi_mushroom.o
     cp shape/zelda_gi_ticketstone/zelda_gi_ticketstone.o gi_ticketstone.o
#     cp shape/zelda_gi_brokensword/zelda_gi_brokensword.o gi_brokensword.o
     cp shape/zelda_js/zelda_js.o Js.o
     cp shape/zelda2_cs/zelda2_cs.o cs.o
#     cp shape/zelda_gi_prescription/zelda_gi_prescription.o gi_prescription.o
#     cp shape/zelda_gi_bracelet/zelda_gi_bracelet.o gi_bracelet.o
     cp shape/zelda_gi_soldout/zelda_gi_soldout.o gi_soldout.o
     cp shape/zelda_gi_frog/zelda_gi_frog.o gi_frog.o
     cp shape/TEXTURE2/ZELDA_MAG2/ZELDA_MAG2.o mag.o
     cp shape/zelda_gt/zelda_gt.o gt.o
#     cp shape/zelda_efc_erupc/zelda_efc_erupc.o efc_erupc.o
#     cp shape/zelda_zl2_anime1/zelda_zl2_anime1.o Zl2_Anime1.o
#     cp shape/zelda_zl2_anime2/zelda_zl2_anime2.o Zl2_Anime2.o
#     cp shape/zelda_gi_golonmask/zelda_gi_golonmask.o gi_golonmask.o
     cp shape/zelda2_gi_goronmask/v2_mask_01.o gi_golonmask.o
#     cp shape/zelda_gi_zoramask/zelda_gi_zoramask.o gi_zoramask.o
     cp shape/zelda2_gi_zoramask/v2_mask_02.o gi_zoramask.o
     cp shape/zelda_gi_gerudomask/zelda_gi_gerudomask.o gi_gerudomask.o
#     cp shape/zelda_ganon2/zelda_ganon2.o B_ganon2.o
#     cp shape/zelda_ganon2_PAL/zelda_ganon2_PAL.o B_ganon2_PAL.o
     cp shape/zelda_ka/zelda_ka.o Ka.o
     cp shape/zelda_ts/zelda_ts.o Ts.o
     cp shape/zelda_zg/zelda_zg.o Zg.o
#     cp shape/zelda_gi_hoverboots/zelda_gi_hoverboots.o gi_hoverboots.o
     cp shape/zelda_gi_m_arrow/zelda_gi_m_arrow.o gi_m_arrow.o
     cp shape/zelda_ds2/zelda_ds2.o Ds2.o
#     cp shape/zelda_ec/zelda_ec.o Ec.o
     cp shape/zelda_fishing/zelda_fishing.o Fish.o
     cp shape/zelda_gi_sutaru/zelda_gi_sutaru.o gi_sutaru.o
#     cp shape/zelda_gi_goddess/zelda_gi_goddess.o gi_goddess.o
     cp shape/zelda2_ssh/zelda2_ssh.o ssh.o
     cp shape/zelda2_bg/zelda2_bg.o Bg.o
     cp shape/zelda2_bombiwa/zelda2_bombiwa.o bombiwa.o
     cp shape/zelda_hintnuts/zelda_hintnuts.o Hintnuts.o
#     cp shape/zelda_rs/zelda_rs.o Rs.o
    cp shape/zelda2_rsn/zelda2_rsn.o Rs.o
#     cp shape/zelda_spot00_break/zelda_spot00_break.o spot00_break.o
     cp shape/zelda2_gla/zelda2_gla.o Gla.o
     cp shape/zelda_shopnuts/zelda_shopnuts.o Shopnuts.o
     cp shape/zelda2_gelb/zelda2_gelb.o Gelb.o
     cp shape/zelda_gr/zelda_gr.o Gr.o
     cp shape/zelda2_dog2/zelda2_dog2.o Dog.o
     cp shape/zelda_jya_iron/zelda_jya_iron.o jya_iron.o
     cp shape/zelda_jya_door/zelda_jya_door.o jya_door.o
     cp shape/zelda_kibako2/zelda_kibako2.o kibako2.o
     cp shape/zelda2_dns/zelda2_dns.o Dns.o
     cp shape/zelda2_dnk/zelda2_dnk.o Dnk.o
#     cp shape/zelda_gi_fire/zelda_gi_fire.o gi_fire.o
     cp shape/zelda_gi_insect/zelda_gi_insect.o gi_insect.o
#     cp shape/zelda_gi_butterfly/zelda_gi_butterfly.o gi_butterfly.o
     cp shape/zelda_gi_ghost/zelda_gi_ghost.o gi_ghost.o
     cp shape/zelda_gi_soul/zelda_gi_soul.o gi_soul.o
     cp shape/zelda_bowl/zelda_bowl.o Bowl.o
#     cp shape/zelda_po_field/zelda_po_field.o Po_Field.o
     cp shape/zelda_demo_kekkai/zelda_demo_kekkai.o Demo_Kekkai.o
     cp shape/zelda_efc_doughnut/zelda_efc_doughnut.o Efc_Doughnut.o
#     cp shape/zelda_gi_dekupouch/zelda_gi_dekupouch.o gi_dekupouch.o
     cp shape/zelda_gi_rupy/zelda_gi_rupy.o gi_rupy.o
#     cp shape/zelda_po_composer/zelda_po_composer.o Po_Composer.o
     cp shape/zelda2_mu/zelda2_mu.o Mu.o
     cp shape/zelda_wf/zelda_wf.o Wf.o
     cp shape/zelda2_skb/zelda2_skb.o Skb.o
     cp shape/zelda_gj/zelda_gj.o gj.o
     cp shape/zelda_geff/zelda_geff.o geff.o
     cp shape/zelda_haka_door/zelda_haka_door.o haka_door.o
     cp shape/zelda_gs/zelda_gs.o gs.o
     cp shape/zelda_ps/zelda_ps.o ps.o
     cp shape/zelda2_omoya_obj/zelda2_omoya_obj.o Bwall.o
     cp shape/zelda_crow/zelda_crow.o Crow.o
     cp shape/zelda_cow/zelda_cow.o Cow.o
#     cp shape/zelda_cob/zelda_cob.o Cob.o
#     cp shape/zelda_gi_sword_1/zelda_gi_sword_1.o gi_sword_1.o
    cp shape/zelda2_gi_sword_1/v2_sword_01.o gi_sword_1.o
#     cp shape/zelda_killer_door/zelda_killer_door.o killer_door.o
     cp shape/zelda_ouke_haka/zelda_ouke_haka.o ouke_haka.o
#     cp shape/zelda2_timeblock/zelda2_timeblock.o timeblock.o
     cp shape/zelda2_zl/zelda2_zl.o Zl4.o
     cp shape/zelda2_kdz/zelda2_kdz.o Kdz.o
     cp shape/zelda2_boyo/zelda2_boyo.o boyo.o
#     cp shape/zelda2_fence/zelda2_fence.o fence.o
#     cp shape/zelda2_hampost/zelda2_hampost.o hampost.o
#     cp shape/zelda2_swfl/zelda2_swfl.o swfl.o
     cp shape/zelda2_fwall/zelda2_fwall.o Fwall.o
     cp shape/zelda2_jso/zelda2_jso.o Jso.o
     cp shape/zelda2_knight/zelda2_knight.o Knight.o
     cp shape/zelda2_icicle/zelda2_icicle.o Icicle.o
     cp shape/zelda2_spdweb/zelda2_spdweb.o Spdweb.o
     cp shape/zelda2_yh/zelda2_yh.o Yh.o
     cp shape/zelda2_boss01/zelda2_boss01.o Boss01.o
     cp shape/zelda2_boss02/zelda2_boss02.o Boss02.o
     cp shape/zelda2_boss03/zelda2_boss03.o Boss03.o
     cp shape/zelda2_boss04/zelda2_boss04.o Boss04.o
     cp shape/zelda2_boss05/zelda2_boss05.o Boss05.o
     cp shape/zelda2_boss06/zelda2_boss06.o Boss06.o
     cp shape/zelda2_boss07/zelda2_boss07.o Boss07.o
     cp shape/zelda2_raf/zelda2_raf.o Raf.o
     cp shape/zelda2_funen/zelda2_funen.o funen.o
     cp shape/zelda2_raillift/zelda2_raillift.o raillift.o
     cp shape/zelda2_numa_obj/zelda2_numa_obj.o numa_obj.o
     cp shape/zelda2_flowerpot/zelda2_flowerpot.o flowerpot.o
     cp shape/zelda2_spinyroll/zelda2_spinyroll.o spinyroll.o
     cp shape/zelda2_ice_block/zelda2_ice_block.o Ice_Block.o
#     cp shape/zelda2_dblue_room/zelda2_dblue_room.o Dblue_Room.o
     cp shape/zelda2_keikoku_demo/zelda2_keikoku_demo.o Keikoku_Demo.o
     cp shape/zelda2_slime/zelda2_slime.o Slime.o
     cp shape/zelda2_pr/zelda2_pr.o Pr.o
     cp shape/zelda2_f52_obj/zelda2_f52_obj.o F52_Obj.o
     cp shape/zelda2_f53_obj/zelda2_f53_obj.o F53_Obj.o
     cp shape/zelda2_kibako/zelda2_kibako.o kibako.o
#     cp shape/zelda2_tsg/zelda2_tsg.o tsg.o
     cp shape/zelda2_sek/zelda2_sek.o tsg.o
     cp shape/zelda2_gmo/zelda2_gmo.o Gmo.o
     cp shape/zelda2_bat/zelda2_bat.o Bat.o
     cp shape/zelda2_sekihi/link/link.o sekihiL.o
     cp shape/zelda2_sekihi/goro/goro.o sekihiG.o
     cp shape/zelda2_sekihi/nut/nut.o sekihiD.o
     cp shape/zelda2_sekihi/zora/zora.o sekihiZ.o
#     cp shape/zelda2_dnc/zelda2_dnc.o Dnc.o
     cp shape/zelda2_wiz/zelda2_wiz.o Wiz.o
     cp shape/zelda2_ladder/zelda2_ladder.o Ladder.o
     cp shape/zelda2_mkk/zelda2_mkk.o Mkk.o
#     cp shape/zelda2_obj_skje/zelda2_obj_skje.o Skje.o
#     cp shape/zelda2_obj_stain/zelda2_obj_stain.o Stain.o
#     cp shape/zelda2_sekihi/toki/toki.o M_Stone.o
     cp shape/zelda2_keikoku_obj/zelda2_keikoku_obj.o Keikoku_Obj.o
     cp shape/zelda2_sichitai_obj/zelda2_sichitai_obj.o Sichitai_Obj.o
     cp shape/zelda2_dekucity_ana_obj/zelda2_dekucity_ana_obj.o Dekucity_Ana_Obj.o
     cp shape/zelda2_rat/zelda2_rat.o Rat.o
     cp shape/zelda2_water_effect/zelda2_water_effect.o Water_Effect.o
     cp shape/zelda2_dblue_object/zelda2_dblue_object.o Dblue_Object.o
     cp shape/zelda2_bal/zelda2_bal.o Bal.o
     cp shape/zelda2_warp_uzu/zelda2_warp_uzu.o Warp_Uzu.o
     cp shape/zelda2_driftice/zelda2_driftice.o driftice.o
     cp shape/zelda2_en_fall/zelda2_en_fall.o Fall.o
     cp shape/zelda2_f40_obj/zelda2_f40_obj.o F40_Obj.o
     cp shape/zelda2_yukimura_obj/zelda2_yukimura_obj.o Yukimura_Obj.o
     cp shape/zelda2_hanareyama_obj/zelda2_hanareyama_obj.o Hanareyama_Obj.o
     cp shape/zelda2_crace_object/zelda2_crace_object.o Crace_Object.o
     cp shape/zelda2_bigslime/zelda2_bigslime.o Bigslime.o
     cp shape/zelda2_dno/zelda2_dno.o Dno.o
     cp shape/zelda2_obj_tokeidai/zelda2_obj_tokeidai.o Obj_Moguri.o
     cp shape/zelda2_eg/zelda2_eg.o Eg.o
     cp shape/zelda2_trU/zelda2_trU.o Tru.o
     cp shape/zelda2_trT/zelda2_trT.o Trt.o
     cp shape/zelda2_hakugin_obj/zelda2_hakugin_obj.o hakugin_obj.o
#     cp shape/zelda2_pfslime/zelda2_pfslime.o Pfslime.o
     cp shape/zelda2_horse_game_check/zelda2_horse_game_check.o Horse_Game_Check.o
     cp shape/zelda2_stk/zelda2_stk.o Stk.o
     cp shape/zelda2_mnk/zelda2_mnk.o Mnk.o
#     cp shape/zelda2_gi_bottle_red/zelda2_gi_bottle_red.o gi_bottle_red.o
     cp shape/zelda2_gi_bottle_0/zelda2_gi_bottle_0.o gi_bottle_red.o
     cp shape/zelda2_tokei_tobira/zelda2_tokei_tobira.o tokei_tobira.o
     cp shape/zelda2_az/zelda2_az.o Az.o
     cp shape/zelda2_twig/zelda2_twig.o Twig.o
     cp shape/zelda2_dekucity_obj/zelda2_dekucity_obj.o dekucity_obj.o
     cp shape/zelda2_po_fusen/zelda2_po_fusen.o Po_Fusen.o
     cp shape/zelda2_racetsubo/zelda2_racetsubo.o racetsubo.o
     cp shape/zelda2_ha/zelda2_ha.o ha.o
     cp shape/zelda2_bigokuta/zelda2_bigokuta.o Bigokuta.o
     cp shape/zelda2_open_obj/zelda2_open_obj.o open_obj.o
     cp shape/zelda2_fu_kaiten/zelda2_fu_kaiten.o Fu_Kaiten.o
     cp shape/zelda2_fu_mato/zelda2_fu_mato.o Fu_Mato.o
     cp shape/zelda2_mtoride/zelda2_mtoride.o Mtoride.o
     cp shape/zelda2_osn/zelda2_osn.o Osn.o
     cp shape/zelda2_tokei_step/zelda2_tokei_step.o tokei_step.o
     cp shape/zelda2_lotus/zelda2_lotus.o Lotus.o
     cp shape/zelda2_tl/zelda2_tl.o Tl.o
     cp shape/zelda2_dkjail_obj/zelda2_dkjail_obj.o dkjail_obj.o
     cp shape/zelda2_visiblock/zelda2_visiblock.o visiblock.o
     cp shape/zelda2_tsn/zelda2_tsn.o Tsn.o
     cp shape/zelda2_ds2n/zelda2_ds2n.o Ds2n.o
     cp shape/zelda2_fsn/zelda2_fsn.o Fsn.o
     cp shape/zelda2_shn/zelda2_shn.o Shn.o
     cp shape/zelda2_sd/zelda2_sd.o sd.o
     cp shape/zelda2_bigicicle/zelda2_bigicicle.o Bigicicle.o
     cp shape/zelda2_gi_bottle_15/v2_bottle_15.o gi_bottle_15.o
     cp shape/zelda2_tk/zelda2_tk.o Tk.o
     cp shape/zelda2_market_obj/zelda2_market_obj.o market_obj.o
     cp shape/zelda2_gi_reserve00/v2_reserve_00.o gi_moon_stone.o
     cp shape/zelda2_gi_reserve01/v2_reserve_01.o gi_kenrisyo.o
     cp shape/zelda2_lightblock/zelda2_lightblock.o lightblock.o
     cp shape/zelda2_takaraya_objects/zelda2_takaraya_objects.o Takaraya_objects.o
     cp shape/zelda2_wdhand/zelda2_wdhand.o Wdhand.o
     cp shape/zelda2_sdn/zelda2_sdn.o Sdn.o
     cp shape/zelda2_snowwd/zelda2_snowwd.o Snowwd.o
     cp shape/zelda2_bji/zelda2_bji.o Bji.o
     cp shape/zelda2_giant/zelda2_giant.o Giant.o
     cp shape/zelda2_comb/zelda2_comb.o comb.o
     cp shape/zelda2_hana/zelda2_hana.o hana.o
     cp shape/zelda2_boss_hakugin/zelda2_boss_hakugin.o Boss_Hakugin.o
     cp shape/zelda2_meganeana_obj/zelda2_meganeana_obj.o Meganeana_Obj.o
     cp shape/zelda2_gi_nutsmask/v2_mask_00.o gi_nutsmask.o
     cp shape/zelda2_stk2/zelda2_stk2.o Stk2.o
     cp shape/zelda2_spot11_obj/zelda2_spot11_obj.o Spot11_Obj.o
     cp shape/zelda2_danpei_object/zelda2_danpei_object.o Danpei_Object.o
     cp shape/zelda2_dhouse/zelda2_dhouse.o dhouse.o
     cp shape/zelda2_hakaisi/zelda2_hakaisi.o Hakaisi.o
     cp shape/zelda_po/zelda_po.o Po.o
     cp shape/zelda2_snowman/zelda2_snowman.o Snowman.o
     cp shape/zelda2_pp/zelda2_pp.o Pp.o
     cp shape/zelda2_goronswitch/zelda2_goronswitch.o goronswitch.o
     cp shape/zelda2_delf/zelda2_delf.o Delf.o
     cp shape/zelda2_botihasira/zelda2_botihasira.o Botihasira.o
     cp shape/zelda2_gi_bigbomb/v2_bigbomb.o gi_bigbomb.o
     cp shape/zelda2_pst/zelda2_pst.o Pst.o
     cp shape/zelda2_bsmask/zelda2_bsmask.o Bsmask.o
     cp shape/zelda2_po_composer/zelda2_po_composer.o Po_Composer.o
     cp shape/zelda2_spidertent/zelda2_spidertent.o spidertent.o
     cp shape/zelda2_zoraegg/zelda2_zoraegg.o zoraegg.o
     cp shape/zelda2_kbt/zelda2_kbt.o kbt.o
     cp shape/zelda2_gg/zelda2_gg.o gg.o
     cp shape/zelda2_maruta/zelda2_maruta.o Maruta.o
     cp shape/zelda2_ghaka/zelda2_ghaka.o ghaka.o 
     cp shape/zelda2_oyu/zelda2_oyu.o oyu.o
     cp shape/zelda2_dnq/zelda2_dnq.o Dnq.o
     cp shape/zelda2_dai/zelda2_dai.o Dai.o
     cp shape/zelda2_kgy/zelda2_kgy.o kgy.o
     cp shape/zelda2_fb/zelda2_fb.o fb.o
     cp shape/zelda2_taisou/zelda2_taisou.o Taisou.o
     cp shape/zelda2_gk/zelda2_gk.o gk.o
     cp shape/zelda2_haka_obj/zelda2_haka_obj.o haka_obj.o
     cp shape/zelda2_dnt/zelda2_dnt.o Dnt.o
     cp shape/zelda2_yukiyama/zelda2_yukiyama.o Yukiyama.o
     cp shape/zelda2_icefloe/zelda2_icefloe.o Icefloe.o
     cp shape/zelda2_gi_bottle_16/v2_bottle_16.o gi_bottle_16.o
     cp shape/zelda2_gi_bottle_22/v2_bottle_22.o gi_bottle_22.o
     cp shape/zelda2_gi_gold_dust/v2_gold_dust.o gi_gold_dust.o
     cp shape/zelda2_bee/zelda2_bee.o Bee.o
     cp shape/zelda2_ot/zelda2_ot.o Ot.o
     cp shape/zelda2_utubo/zelda2_utubo.o Utubo.o
     cp shape/zelda2_dora/zelda2_dora.o Dora.o
     cp shape/zelda2_gi_seahorse/zelda2_gi_seahorse.o gi_seahorse.o
     cp shape/zelda2_gi_loach/zelda2_gi_loach.o gi_loach.o
     cp shape/zelda2_bigpo/zelda2_bigpo.o Bigpo.o
     cp shape/zelda2_hariko/zelda2_hariko.o Hariko.o
     cp shape/zelda2_dnj/zelda2_dnj.o Dnj.o
     cp shape/zelda2_sinkai_kabe/zelda2_sinkai_kabe.o Sinkai_Kabe.o
     cp shape/zelda2_kin2_obj/zelda2_kin2_obj.o kin2_obj.o
     cp shape/zelda2_ishi/zelda2_ishi.o ishi.o
     cp shape/zelda2_hakugin_demo/zelda2_hakugin_demo.o Hakugin_Demo.o
     cp shape/zelda2_jg/zelda2_jg.o jg.o
     cp shape/zelda2_gi_sword_2/v2_sword_02.o gi_sword_2.o
     cp shape/zelda2_gi_sword_3/v2_sword_03.o gi_sword_3.o
     cp shape/zelda2_gi_sword_4/v2_sword_04.o gi_sword_4.o
     cp shape/zelda2_um/zelda2_um.o um.o
     cp shape/zelda2_rb/zelda2_rb.o Rb.o
     cp shape/zelda2_mbar_obj/zelda2_mbar_obj.o mbar_obj.o
     cp shape/zelda2_ikana_obj/zelda2_ikana_obj.o ikana_obj.o
     cp shape/zelda2_kz/zelda2_kz.o Kz.o
     cp shape/zelda2_tokei_turret/zelda2_tokei_turret.o tokei_turret.o
     cp shape/zelda2_zog/zelda2_zog.o Zog.o
     cp shape/zelda2_rotlift/zelda2_rotlift.o Rotlift.o
     cp shape/zelda2_posthouse_obj/zelda2_posthouse_obj.o Posthouse_obj.o
     cp shape/zelda2_gi_mask09/v2_mask_09.o gi_jsonmask.o
     cp shape/zelda2_gi_mask14/v2_mask_14.o gi_bigelfmask.o
     cp shape/zelda2_gi_mask15/v2_mask_15.o gi_gibudomask.o
     cp shape/zelda2_inibs_object/zelda2_inibs_object.o Inibs_Object.o
     cp shape/zelda2_tree/zelda2_tree.o Tree.o
     cp shape/zelda2_kaizoku_obj/zelda2_kaizoku_obj.o Kaizoku_obj.o
     cp shape/zelda2_gi_reserve_b_00/v2_reserve_b_00.o gi_inn_key.o
     cp shape/zelda2_gi_reserve_c_00/v2_reserve_c_00.o gi_c_letter.o
     cp shape/zelda2_zob/zelda2_zob.o Zob.o
     cp shape/zelda2_milkbar/zelda2_milkbar.o Milkbar.o
     cp shape/zelda2_dmask/zelda2_dmask.o Dmask.o
     cp shape/zelda2_gi_reserve_c_01/v2_reserve_c_01.o gi_pendant.o
     cp shape/zelda2_zod/zelda2_zod.o Zod.o
     cp shape/zelda2_kumo30/zelda2_kumo30.o Kumo30.o
     cp shape/zelda2_yasi/zelda2_yasi.o Yasi.o
     cp shape/zelda2_tanron1/zelda2_tanron1.o Tanron1.o
     cp shape/zelda2_tanron2/zelda2_tanron2.o Tanron2.o
     cp shape/zelda2_tanron3/zelda2_tanron3.o Tanron3.o
     cp shape/zelda2_gi_mushroom/v2_mushroom.o gi_mushroom.o
