#!/usr/local/bin/bash
#set -x
#
# $Id$
#
# $Log$
# Revision 1.81  1997/12/18  04:10:51  umemiya
# *** empty log message ***
#
# Revision 1.80  1997/12/17  07:03:14  tarukado
# *** empty log message ***
#
# Revision 1.79  1997/12/17  04:57:10  umemiya
# 森の神殿・オブジェ追加
#
# Revision 1.78  1997/12/16  05:59:21  sumiyosi
# *** empty log message ***
#
# Revision 1.77  1997/12/16  00:54:29  matutani
# ファントムガノン馬
#
# Revision 1.76  1997/12/12  02:10:36  tarukado
# *** empty log message ***
#
# Revision 1.75  1997/12/12  01:52:00  tarukado
# *** empty log message ***
#
# Revision 1.74  1997/12/11  06:57:27  tarukado
# *** empty log message ***
#
# Revision 1.73  1997/12/04  09:42:29  umemiya
# 水の神殿・MOVEBGオブジェ追加
#
# Revision 1.72  1997/11/28  00:46:28  sumiyosi
# *** empty log message ***
#
# Revision 1.71  1997/11/26  07:33:26  umemiya
# バリ追加
#
# Revision 1.70  1997/11/18  04:46:20  sumiyosi
# *** empty log message ***
#
# Revision 1.69  1997/11/14  07:32:49  sumiyosi
# コキリ族軍団追加
#
# Revision 1.68  1997/11/12  08:21:34  umemiya
# 面クリダンジョンオブジェクト追加
#
# Revision 1.67  1997/11/12  07:03:41  sumiyosi
# *** empty log message ***
#
# Revision 1.66  1997/11/08  08:37:53  umemiya
# デクナッツ追加
#
# Revision 1.65  1997/11/07  04:05:52  iwawaki
# *** empty log message ***
#
# Revision 1.64  1997/10/25  05:44:13  iwawaki
# *** empty log message ***
#
# Revision 1.63  1997/10/21  09:14:32  matutani
# ゼルダ馬
#
# Revision 1.62  1997/10/20  10:45:48  sumiyosi
# ハイリア住民さらに追加。
#
# Revision 1.61  1997/10/19  09:03:22  iwawaki
# *** empty log message ***
#
# Revision 1.60  1997/10/17  08:26:27  sumiyosi
# ハイリアの住民追加。
#
# Revision 1.59  1997/10/16  08:44:16  sumiyosi
# En_GirlB→子ゼルダに変更。
#
# Revision 1.58  1997/10/08  14:18:04  sumiyosi
# インパ（マスク付）追加
#
# Revision 1.57  1997/10/08  02:28:05  sumiyosi
# ゴロン族追加
#
# Revision 1.56  1997/10/02  13:44:58  umemiya
# *** empty log message ***
#
# Revision 1.55  1997/10/02  12:40:30  umemiya
# デクババ追加
#
# Revision 1.54  1997/10/01  04:31:43  tarukado
# がノンドロフ ＆ アモス 追加
#
# Revision 1.53  1997/10/01  02:37:59  umemiya
# *** empty log message ***
#
# Revision 1.52  1997/10/01  02:26:14  hayakawa
# 日付比較コピー
#
# Revision 1.51  1997/09/29  11:50:51  umemiya
# 妖精ダンジョンオブジェ追加
#
# Revision 1.50  1997/09/29  10:54:54  sumiyosi
# コキリ族の女の子追加
#
# Revision 1.49  1997/09/27  02:05:28  hayakawa
# set -xをコメントアウトした
#
# Revision 1.48  1997/09/26  06:32:40  sumiyosi
# *** empty log message ***
#
# Revision 1.47  1997/09/24  07:30:46  tarukado
# *** empty log message ***
#
# Revision 1.46  1997/09/20  04:16:41  tarukado
# *** empty log message ***
#
# Revision 1.45  1997/09/19  08:57:12  tarukado
# *** empty log message ***
#
# Revision 1.44  1997/09/19  05:29:29  tarukado
# モリブリン追加
#
# Revision 1.43  1997/09/17  13:51:39  umemiya
# spot00オブジェ追加
#
# Revision 1.42  1997/09/17  07:24:54  sumiyosi
# *** empty log message ***
#
# Revision 1.41  1997/09/16  08:47:02  sumiyosi
# *** empty log message ***
#
# Revision 1.40  1997/09/12  12:29:05  matutani
# ガノン馬追加
#
# Revision 1.39  1997/09/11  06:45:09  umemiya
# 火の神殿オブジェ追加
#
# Revision 1.38  1997/09/09  11:54:28  iwawaki
# *** empty log message ***
#
# Revision 1.37  1997/09/05  06:37:10  sumiyosi
# *** empty log message ***
#
# Revision 1.36  1997/09/05  06:35:29  matutani
# *** empty log message ***
#
# Revision 1.35  1997/09/01  02:13:16  tarukado
# *** empty log message ***
#
# Revision 1.34  1997/09/01  01:03:48  tarukado
# *** empty log message ***
#
# Revision 1.33  1997/08/27  11:30:37  sumiyosi
# *** empty log message ***
#
# Revision 1.32  1997/08/27  06:05:06  sumiyosi
# *** empty log message ***
#
# Revision 1.31  1997/08/25  13:37:44  sumiyosi
# スタルチュラ追加。
#
# Revision 1.30  1997/08/25  01:51:32  sumiyosi
# *** empty log message ***
#
# Revision 1.29  1997/08/25  01:49:30  sumiyosi
# *** empty log message ***
#
# Revision 1.28  1997/08/25  01:48:38  hayakawa
# *** empty log message ***
#
# Revision 1.27  1997/08/19  09:46:25  tarukado
# *** empty log message ***
#
# Revision 1.26  1997/08/12  11:11:00  iwawaki
# *** empty log message ***
#
# Revision 1.25  1997/08/05  09:29:58  tarukado
# *** empty log message ***
#
# Revision 1.24  1997/08/04  02:38:22  iwawaki
# *** empty log message ***
#
# Revision 1.23  1997/07/30  01:25:20  tarukado
# *** empty log message ***
#
# Revision 1.22  1997/07/18  11:24:31  tarukado
# *** empty log message ***
#
# Revision 1.21  1997/07/18  01:16:01  tarukado
# *** empty log message ***
#
# Revision 1.20  1997/07/17  09:49:45  iwawaki
# *** empty log message ***
#
# Revision 1.19  1997/07/17  08:39:26  tarukado
# *** empty log message ***
#
# Revision 1.18  1997/07/17  06:25:26  tarukado
# *** empty log message ***
#
# Revision 1.17  1997/07/17  06:08:48  tarukado
# *** empty log message ***
#
# Revision 1.16  1997/07/17  02:50:13  tarukado
# *** empty log message ***
#
# Revision 1.15  1997/07/17  02:49:41  tarukado
# *** empty log message ***
#
# Revision 1.14  1997/07/17  02:35:34  tarukado
# *** empty log message ***
#
# Revision 1.13  1997/07/17  01:46:25  tarukado
# *** empty log message ***
#
# Revision 1.12  1997/07/09  08:37:57  sumiyosi
# *** empty log message ***
#
# Revision 1.11  1997/07/09  07:22:03  iwawaki
# *** empty log message ***
#
# Revision 1.10  1997/07/02  09:03:44  tarukado
# *** empty log message ***
#
# Revision 1.9  1997/07/02  08:04:50  tarukado
# *** empty log message ***
#
# Revision 1.8  1997/06/26  12:33:43  iwawaki
# *** empty log message ***
#
# Revision 1.7  1997/06/19  00:42:49  iwawaki
# *** empty log message ***
#
# Revision 1.6  1997/06/06  06:57:42  iwawaki
# *** empty log message ***
#
# Revision 1.5  1997/06/06  05:48:25  iwawaki
# *** empty log message ***
#
# Revision 1.4  1997/06/05  07:49:04  iwawaki
# *** empty log message ***
#
# Revision 1.3  1997/06/05  07:18:12  iwawaki
# *** empty log message ***
#
# Revision 1.2  1997/05/26  10:26:49  iwawaki
# *** empty log message ***
#
# Revision 1.1  1997/05/26  06:37:52  iwawaki
# Initial revision
#

cp2() {
  if [ ! -e $2 -o $1 -nt $2 ]; then
    echo    cp $1 $2
    command cp $1 $2
  fi
}
cp() {
  SRC=$1
  DEST=$2
  SRCBASE=`basename $SRC`
  if [ -d $DEST ]; then
    cp2 $SRC $DEST/$SRCBASE
  else
    cp2 $SRC $DEST
  fi
}

     cp shape/zelda_field_keep/zelda_field_keep.o Field_keep.o
     cp shape/zelda_dangeon_keep/zelda_dangeon_keep.o Dangeon_keep.o
     cp shape/zelda_link/Anime_Data/Anime_Data.o Link_anime_data.o
     cp shape/zelda_link/Skeleton/Boy/Boy.o Link_boy.o
     cp shape/zelda_link/Skeleton/Child/Child.o Link_child.o
     cp shape/zelda_baby_skel/zelda_baby_skel.o Baby_skel.o 
     cp shape/zelda_box/zelda_box.o Box.o
     cp shape/zelda_dodongo/zelda_dodongo.o Dodongo.o
     cp shape/zelda_fire/zelda_fire.o Fire.o
     cp shape/zelda_human/zelda_human.o Human.o
     cp shape/zelda_ironknack/zelda_ironknack.o Ironknack.o
     cp shape/zelda_nw/zelda_nw.o Niw.o
     cp shape/zelda_rock/zelda_rock.o Rock.o
     cp shape/zelda_skelton/zelda_skelton.o Skelton.o
     cp shape/zelda_slime/zelda_slime.o Slime.o
     cp shape/zelda_soldier/zelda_soldier.o Soldier.o
     cp shape/zelda_st/zelda_st.o St.o
     cp shape/zelda_tt/zelda_tt.o Tite.o
     cp shape/zelda_rb/zelda_rb.o Reeba.o
     cp shape/zelda_ph/zelda_ph.o Peehat.o
     cp shape/zelda_horse/zelda_horse.o Horse.o
     cp shape/zelda_zf/zelda_zf.o Zf.o
     cp shape/zelda_goma/zelda_goma.o Go.o
     cp shape/zelda_kdodongo/zelda_kdodongo.o Kdodongo.o
     cp shape/zelda_zl1/zelda_zl1.o Zl1.o
     cp shape/zelda_ff/zelda_ff.o Ff.o
     cp shape/zelda_wm/zelda_wm.o Wm.o
     cp shape/zelda_po/zelda_po.o Po.o
     cp shape/zelda_oAx/zelda_oAx.o OAX.o
     cp shape/zelda_oc/zelda_oc.o Oc.o
     cp shape/zelda_th/zelda_th.o Th.o
     cp shape/zelda_tg2/zelda_tg2.o Tg2.o
     cp shape/zelda_kogoma/zelda_kogoma.o Gol.o
     cp shape/zelda_bubble/zelda_bubble.o Bubble.o
     cp shape/zelda_dodojr/zelda_dodojr.o Dodojr.o
     cp shape/zelda_torch2/zelda_torch2.o Torch2.o
     cp shape/zelda_bl/zelda_bl.o Bl.o
     cp shape/zelda_tp/zelda_tp.o Tp.o
     cp shape/zelda_bw/zelda_bw.o Bw.o
     cp shape/zelda_ei/zelda_ei.o Ei.o
     cp shape/zelda_horse_normal/zelda_horse_normal.o Horse_Normal.o
     cp shape/zelda_oBx/zelda_oBx.o OBX.o
     cp shape/zelda_o_anime/zelda_o_anime.o O_anime.o
     cp shape/zelda_spo04_objects/zelda_spo04_objects.o spot04_objects.o
     cp shape/zelda_ddan_objects/zelda_ddan_objects.o ddan_objects.o
     cp shape/zelda_hidan_objects/zelda_hidan_objects.o hidan_objects.o
     cp shape/zelda_horse_ganon/zelda_horse_ganon.o Horse_Ganon.o
     cp shape/zelda_oA2/zelda_oA2.o OA2.o
     cp shape/zelda_spot00_objects/zelda_spot00_objects.o spot00_objects.o
     cp shape/zelda_mb/zelda_mb.o Mb.o
     cp shape/zelda_bombf/zelda_bombf.o Bombf.o
     cp shape/zelda_sk2/zelda_sk2.o Sk2.o
     cp shape/zelda_oE1/zelda_oE1.o OE1.o
     cp shape/zelda_oE_anime/zelda_oE_anime.o OE_anime.o
     cp shape/zelda_oE2/zelda_oE2.o OE2.o
     cp shape/zelda_ydan_objects/zelda_ydan_objects.o ydan_objects.o
     cp shape/zelda_gnd/zelda_gnd.o Gnd.o
     cp shape/zelda_am/zelda_am.o Am.o
     cp shape/zelda_dekubaba/zelda_dekubaba.o Dekubaba.o
     cp shape/zelda_oF1/zelda_oF1.o OF1.o
     cp shape/zelda_oA3/zelda_oA3.o OA3.o
     cp shape/zelda_oA4/zelda_oA4.o OA4.o
     cp shape/zelda_oA5/zelda_oA5.o OA5.o
     cp shape/zelda_oA6/zelda_oA6.o OA6.o
     cp shape/zelda_oA7/zelda_oA7.o OA7.o
     cp shape/zelda_jj/zelda_jj.o Jj.o
     cp shape/zelda_oA8/zelda_oA8.o OA8.o
     cp shape/zelda_oA9/zelda_oA9.o OA9.o
     cp shape/zelda_oB2/zelda_oB2.o OB2.o
     cp shape/zelda_oB3/zelda_oB3.o OB3.o
     cp shape/zelda_oB4/zelda_oB4.o OB4.o
     cp shape/zelda_horse_zelda/zelda_horse_zelda.o Horse_Zelda.o
     cp shape/zelda_opdemo1/zelda_opdemo1.o Opening_Demo1.o
     cp shape/zelda_warp1/zelda_warp1.o Warp1.o
     cp shape/zelda_b_heart/zelda_b_heart.o B_heart.o
     cp shape/zelda_dekunuts/zelda_dekunuts.o Dekunuts.o
     cp shape/zelda_oE3/zelda_oE3.o OE3.o
     cp shape/zelda_oE4/zelda_oE4.o OE4.o
     cp shape/zelda_menkuri_objects/zelda_menkuri_objects.o menkuri_objects.o
     cp shape/zelda_oE5/zelda_oE5.o OE5.o
     cp shape/zelda_oE6/zelda_oE6.o OE6.o
     cp shape/zelda_oE7/zelda_oE7.o OE7.o
     cp shape/zelda_oE8/zelda_oE8.o OE8.o
     cp shape/zelda_oE9/zelda_oE9.o OE9.o
     cp shape/zelda_oE10/zelda_oE10.o OE10.o
     cp shape/zelda_oE11/zelda_oE11.o OE11.o
     cp shape/zelda_oE12/zelda_oE12.o OE12.o
     cp shape/zelda_vali/zelda_vali.o Vali.o
     cp shape/zelda_oA10/zelda_oA10.o OA10.o
     cp shape/zelda_oA11/zelda_oA11.o OA11.o
     cp shape/zelda_mizu_objects/zelda_mizu_objects.o mizu_objects.o
     cp shape/zelda_fantomHG/zelda_fantomHG.o FantomHG.o
     cp shape/zelda_oB1/zelda_oB1.o OB1.o
     cp shape/zelda_mori_hineri1/zelda_mori_hineri1.o mori_hineri1.o
     cp shape/zelda_bb/zelda_bb.o Bb.o
